#!/usr/bin/env python3
"""Generate docker/compose.yml and docker/env/<slug>.env.example from the registry.

The registry is already the right input: tools/maintainer/skills.json carries the
binary names and versions, and each skills/<slug>/manifest.json carries the
credential schema. This mirrors build-catalog.py: the output is committed and
gated by check_compose.py, so a drifted generator fails CI rather than shipping.

Run: python3 tools/maintainer/build_compose.py
"""

import json
import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SKILLS_JSON = REPO / "tools" / "maintainer" / "skills.json"
DOCKER = REPO / "docker"
ENV_DIR = DOCKER / "env"

GENERATED_BANNER = "# GENERATED by tools/maintainer/build_compose.py - DO NOT EDIT."

# Defaults are deliberately generous rather than tuned. A connector forks a
# static binary per mirror call and sets mmap_size=256MB, so resident memory
# looks alarming without being a leak. Operators raise these per service in
# compose.override.yml.
DEFAULT_MEM_LIMIT = "512m"
DEFAULT_PIDS_LIMIT = 512

# The container runs as this uid; the image creates /data and chowns it. Named
# volumes inherit that ownership. Bind mounts do NOT, and need a manual chown.
RUN_UID = 10001


def load_registry():
    data = json.loads(SKILLS_JSON.read_text())
    return data["skills"]


def connector_slugs(skills):
    out = []
    for slug in sorted(skills):
        if (REPO / "skills" / slug / "cli").is_dir():
            out.append(slug)
    return out


def mcp_main(slug):
    hits = sorted((REPO / "skills" / slug / "cli" / "cmd").glob("*-mcp/main.go"))
    return hits[0] if hits else None


def supports_http(slug):
    """True when the printed MCP server can serve streamable HTTP.

    Detected from source rather than trusted from the registry, because a
    reprint can change it. check_compose.py asserts the two agree.
    """
    main = mcp_main(slug)
    if main is None:
        return False
    src = main.read_text()
    return "PP_MCP_TRANSPORT" in src or "NewStreamableHTTPServer" in src


def supports_no_config_write(slug):
    """True when the CLI honours <PREFIX>_NO_CONFIG_WRITE (Servosity#270).

    Where it exists the generated service sets it, so a credential minted at
    runtime never lands in the volume the operator backs up.
    """
    internal = REPO / "skills" / slug / "cli" / "internal"
    if not internal.is_dir():
        return None
    for path in internal.rglob("*.go"):
        if path.name.endswith("_test.go"):
            continue
        m = re.search(r'"([A-Z][A-Z0-9_]*_NO_CONFIG_WRITE)"', path.read_text())
        if m:
            return m.group(1)
    return None


def manifest_env(slug):
    """Return [(ENV_NAME, required, sensitive, description)] for a connector."""
    path = REPO / "skills" / slug / "manifest.json"
    if not path.is_file():
        return []
    man = json.loads(path.read_text())
    env = (man.get("server") or {}).get("mcp_config", {}).get("env") or {}
    user_config = man.get("user_config") or {}
    rows = []
    for name, ref in sorted(env.items()):
        key = None
        m = re.fullmatch(r"\$\{user_config\.([A-Za-z0-9_]+)\}", str(ref).strip())
        if m:
            key = m.group(1)
        uc = user_config.get(key, {}) if key else {}
        rows.append(
            (
                name,
                bool(uc.get("required", False)),
                bool(uc.get("sensitive", False)),
                (uc.get("description") or "").strip(),
            )
        )
    return rows


def wrap_comment(text, width=76):
    words = text.split()
    lines, cur = [], ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > width:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    return lines


def render_env_example(slug, rows):
    out = [
        GENERATED_BANNER,
        f"# Credentials for the {slug} connector.",
        "#",
        "# Copy to docker/env/%s.env and fill in. That file is gitignored." % slug,
        "# Values here are visible to anyone who can run `docker inspect`; see",
        "# docker/README.md for the graduation path to a secret store.",
        "",
    ]
    if not rows:
        out += [
            "# This connector's manifest declares no environment credentials.",
            f"# See skills/{slug}/README.md for how it authenticates.",
            "",
        ]
        return "\n".join(out)
    for name, required, sensitive, desc in rows:
        tag = "required" if required else "optional"
        if sensitive:
            tag += ", secret"
        out.append(f"# [{tag}]")
        for line in wrap_comment(desc):
            out.append(f"# {line}")
        out.append(f"{name}=" if required else f"# {name}=")
        out.append("")
    return "\n".join(out)


def render_service(slug, skills, http, ncw_var):
    entry = skills[slug]
    cli_binary = entry.get("cli_binary", f"{slug}-cli")
    mcp_binary = entry.get("mcp_binary", f"{slug}-mcp")
    version_var = slug.upper().replace("-", "_") + "_VERSION"
    version = entry.get("version", "")

    lines = []
    lines.append(f"  {slug}:")
    lines.append(f"    profiles: [{slug}]")
    # One level of interpolation only: Compose handles a nested ${A:-${B:-c}}
    # inconsistently across versions. Per-connector pins beat a global tag here
    # anyway, because skills.json is repo-global and a `git pull` moves all 64
    # versions at once. The pin lives in docker/.env, which is never regenerated.
    lines.append(
        f'    image: "${{MSP_IMAGE_REPO:-msp-skills}}/{slug}:${{{version_var}:-{version}}}"'
    )
    lines.append("    build:")
    lines.append("      context: ..")
    lines.append("      dockerfile: docker/Dockerfile.connector")
    lines.append("      args:")
    lines.append(f"        SLUG: {slug}")
    lines.append(f"        CLI_BINARY: {cli_binary}")
    lines.append(f"        MCP_BINARY: {mcp_binary}")
    lines.append(f'        VERSION: "${{{version_var}:-{version}}}"')
    lines.append(f"    container_name: msp-{slug}")
    lines.append("    env_file:")
    lines.append(f"      - env/{slug}.env")
    lines.append("    environment:")
    # HOME is the one lever that relocates storage for all 64 connectors: 54 of
    # them build their paths from os.UserHomeDir() and never consult XDG.
    lines.append("      HOME: /data")
    if http:
        lines.append("      PP_MCP_TRANSPORT: http")
    if ncw_var:
        # Keeps a runtime-minted token out of the backed-up volume. Only some
        # connectors honour this today; see docker/README.md.
        lines.append(f'      {ncw_var}: "1"')
    lines.append(f"    user: \"{RUN_UID}:{RUN_UID}\"")
    lines.append("    volumes:")
    lines.append(f"      - msp-{slug}-data:/data")
    lines.append("    networks: [msp-internal]")
    # No ports. The gateway is the only published surface, which is what makes
    # its audit log a record of every call rather than a record of polite ones.
    lines.append("    read_only: true")
    lines.append("    tmpfs:")
    lines.append("      - /tmp")
    lines.append("    restart: unless-stopped")
    lines.append(f"    mem_limit: {DEFAULT_MEM_LIMIT}")
    lines.append(f"    pids_limit: {DEFAULT_PIDS_LIMIT}")
    lines.append("    security_opt:")
    lines.append("      - no-new-privileges:true")
    lines.append("    cap_drop:")
    lines.append("      - ALL")
    return "\n".join(lines)


def render_root_env(slugs, skills):
    """docker/.env.example: operator-owned settings, including version pins.

    skills.json is repo-global, so `git pull` moves every connector's version at
    once. Pinning here is what stops an unrelated upgrade riding along, and it is
    also half of a rollback: an older binary refuses a newer store schema, so the
    volume must be snapshotted before the pin moves.
    """
    out = [
        GENERATED_BANNER,
        "# Copy to docker/.env and edit. Unlike docker/env/<slug>.env this file",
        "# holds no credentials, only deployment settings.",
        "",
        "# Which connectors start. Comma-separated, no spaces.",
        "# COMPOSE_PROFILES=halopsa,immybot",
        "",
        "# Image name prefix. Change if you push these to your own registry.",
        "# MSP_IMAGE_REPO=msp-skills",
        "",
        "# Version pins, one per connector. Uncomment to hold a connector at a",
        "# known-good version. Snapshot that connector's volume BEFORE lowering a",
        "# pin: an older binary refuses a store schema written by a newer one, so",
        "# a rollback without a snapshot is a one-way door.",
        "",
    ]
    for slug in slugs:
        var = slug.upper().replace("-", "_") + "_VERSION"
        out.append(f"# {var}={skills[slug].get('version','')}")
    out.append("")
    return "\n".join(out)


def main(out_dir=None):
    """Write the generated files. out_dir defaults to docker/.

    check_compose.py passes a temp directory so it can diff without touching the
    working tree: a gate that repairs what it is checking will pass on a re-run
    and silently discard whatever the operator had edited.
    """
    docker = Path(out_dir) if out_dir else DOCKER
    env_dir = docker / "env"
    skills = load_registry()
    slugs = connector_slugs(skills)

    header = [
        GENERATED_BANNER,
        "# Regenerate: python3 tools/maintainer/build_compose.py",
        "# Gated by:   python3 tools/maintainer/check_compose.py",
        "#",
        "# One service per connector, each behind its own Compose profile, so",
        "# `docker compose --profile halopsa up -d` runs exactly one.",
        "#",
        "# No connector publishes a port. Do not add `ports:` to a service here:",
        "# the MCP servers have no authentication of their own, so publishing one",
        "# puts a fully privileged, unauthenticated server on the LAN.",
        "# check_compose.py fails on it.",
        "",
        "name: msp-skills",
        "",
        "services:",
    ]

    body, stdio_only, ncw_supported = [], [], []
    for slug in slugs:
        http = supports_http(slug)
        ncw = supports_no_config_write(slug)
        if not http:
            stdio_only.append(slug)
        if ncw:
            ncw_supported.append(slug)
        body.append(render_service(slug, skills, http, ncw))

    footer = [
        "",
        "networks:",
        "  msp-internal:",
        "    driver: bridge",
        "    # Not `internal: true`: connectors must reach their vendor APIs.",
        "    # Isolation comes from publishing no ports, not from blocking egress.",
        "",
        "volumes:",
    ]
    for slug in slugs:
        footer.append(f"  msp-{slug}-data:")
    footer.append("")

    compose = "\n".join(header) + "\n" + "\n\n".join(body) + "\n" + "\n".join(footer)
    docker.mkdir(parents=True, exist_ok=True)
    env_dir.mkdir(parents=True, exist_ok=True)
    (docker / "compose.yml").write_text(compose)

    for slug in slugs:
        (env_dir / f"{slug}.env.example").write_text(
            render_env_example(slug, manifest_env(slug))
        )

    (docker / ".env.example").write_text(render_root_env(slugs, skills))

    print(f"wrote docker/compose.yml ({len(slugs)} connector services)")
    print("wrote docker/.env.example")
    print(f"wrote docker/env/<slug>.env.example ({len(slugs)} files)")
    if stdio_only:
        print(
            f"note: {len(stdio_only)} connector(s) cannot serve HTTP and are "
            f"unreachable through the gateway until fixed: {', '.join(stdio_only)}"
        )
    print(
        f"note: {len(ncw_supported)} of {len(slugs)} connector(s) honour "
        f"NO_CONFIG_WRITE: {', '.join(ncw_supported) if ncw_supported else 'none'}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else None))
