// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Addon struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type AddonList struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type ApException struct {
	ActionNeeded         string `json:"actionNeeded"`
	AddedBy              string `json:"addedBy"`
	AttachmentMd5        string `json:"attachmentMd5"`
	Comment              string `json:"comment"`
	EditedBy             string `json:"editedBy"`
	EntityId             string `json:"entityId"`
	IgnoringSpfCheck     bool   `json:"ignoringSpfCheck"`
	LinkDomainMatching   string `json:"linkDomainMatching"`
	LinkDomains          string `json:"linkDomains"`
	MatchOnlyFuture      bool   `json:"matchOnlyFuture"`
	QuarantineAll        bool   `json:"quarantineAll"`
	Recipient            string `json:"recipient"`
	RecipientMatching    string `json:"recipientMatching"`
	SenderClientIp       string `json:"senderClientIp"`
	SenderDomain         string `json:"senderDomain"`
	SenderDomainMatching string `json:"senderDomainMatching"`
	SenderEmail          string `json:"senderEmail"`
	SenderEmailMatching  string `json:"senderEmailMatching"`
	SenderIp             string `json:"senderIp"`
	SenderName           string `json:"senderName"`
	SenderNameMatching   string `json:"senderNameMatching"`
	Subject              string `json:"subject"`
	SubjectMatching      string `json:"subjectMatching"`
	UpdateTime           string `json:"updateTime"`
}

type ApExceptionBlacklistCreate struct {
	ActionNeeded         string `json:"actionNeeded"`
	AttachmentMd5        string `json:"attachmentMd5"`
	Comment              string `json:"comment"`
	EntityId             string `json:"entityId"`
	IgnoringSpfCheck     bool   `json:"ignoringSpfCheck"`
	LinkDomainMatching   string `json:"linkDomainMatching"`
	LinkDomains          string `json:"linkDomains"`
	MatchOnlyFuture      bool   `json:"matchOnlyFuture"`
	QuarantineAll        bool   `json:"quarantineAll"`
	Recipient            string `json:"recipient"`
	RecipientMatching    string `json:"recipientMatching"`
	SenderClientIp       string `json:"senderClientIp"`
	SenderDomain         string `json:"senderDomain"`
	SenderDomainMatching string `json:"senderDomainMatching"`
	SenderEmail          string `json:"senderEmail"`
	SenderEmailMatching  string `json:"senderEmailMatching"`
	SenderIp             string `json:"senderIp"`
	SenderName           string `json:"senderName"`
	SenderNameMatching   string `json:"senderNameMatching"`
	Subject              string `json:"subject"`
	SubjectMatching      string `json:"subjectMatching"`
}

type ApExceptionBlacklistCreateRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type ApExceptionListResponse struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type ApExceptionWhitelistCreate struct {
	ActionNeeded         string `json:"actionNeeded"`
	AttachmentMd5        string `json:"attachmentMd5"`
	Comment              string `json:"comment"`
	EntityId             string `json:"entityId"`
	IgnoringSpfCheck     bool   `json:"ignoringSpfCheck"`
	LinkDomainMatching   string `json:"linkDomainMatching"`
	LinkDomains          string `json:"linkDomains"`
	MatchOnlyFuture      bool   `json:"matchOnlyFuture"`
	QuarantineAll        bool   `json:"quarantineAll"`
	Recipient            string `json:"recipient"`
	RecipientMatching    string `json:"recipientMatching"`
	SenderClientIp       string `json:"senderClientIp"`
	SenderDomain         string `json:"senderDomain"`
	SenderDomainMatching string `json:"senderDomainMatching"`
	SenderEmail          string `json:"senderEmail"`
	SenderEmailMatching  string `json:"senderEmailMatching"`
	SenderIp             string `json:"senderIp"`
	SenderName           string `json:"senderName"`
	SenderNameMatching   string `json:"senderNameMatching"`
	Subject              string `json:"subject"`
	SubjectMatching      string `json:"subjectMatching"`
}

type ApExceptionWhitelistCreateRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type AvailableEventAction struct {
	ActionName      string          `json:"actionName"`
	ActionParameter json.RawMessage `json:"actionParameter"`
}

type CombinedVerdict struct {
	Ap                  string `json:"ap"`
	Av                  string `json:"av"`
	ClicktimeProtection string `json:"clicktimeProtection"`
	Dlp                 string `json:"dlp"`
	ShadowIt            string `json:"shadowIt"`
}

type EmailEntityAttachment struct {
	MD5      string `json:"MD5"`
	Mimetype string `json:"mimetype"`
	Name     string `json:"name"`
	Size     int    `json:"size"`
}

type EmailEntityPayload struct {
	SpfResult                string          `json:"SpfResult"`
	AttachmentCount          int             `json:"attachmentCount"`
	Attachments              json.RawMessage `json:"attachments"`
	Bcc                      json.RawMessage `json:"bcc"`
	BccUser                  json.RawMessage `json:"bccUser"`
	Cc                       json.RawMessage `json:"cc"`
	CcUser                   json.RawMessage `json:"ccUser"`
	EmailLinks               json.RawMessage `json:"emailLinks"`
	FromDomain               string          `json:"fromDomain"`
	FromEmail                string          `json:"fromEmail"`
	FromName                 string          `json:"fromName"`
	FromUser                 string          `json:"fromUser"`
	InternetMessageId        string          `json:"internetMessageId"`
	IsDeleted                bool            `json:"isDeleted"`
	IsIncoming               bool            `json:"isIncoming"`
	IsInternal               bool            `json:"isInternal"`
	IsOutgoing               bool            `json:"isOutgoing"`
	IsQuarantineNotification bool            `json:"isQuarantineNotification"`
	IsQuarantined            bool            `json:"isQuarantined"`
	IsRead                   bool            `json:"isRead"`
	IsRestoreDeclined        bool            `json:"isRestoreDeclined"`
	IsRestoreRequested       bool            `json:"isRestoreRequested"`
	IsRestored               bool            `json:"isRestored"`
	Mode                     string          `json:"mode"`
	Received                 string          `json:"received"`
	Recipients               json.RawMessage `json:"recipients"`
	ReplyToEmail             string          `json:"replyToEmail"`
	ReplyToNickname          string          `json:"replyToNickname"`
	SaasSpamVerdict          string          `json:"saasSpamVerdict"`
	Size                     int             `json:"size"`
	Subject                  string          `json:"subject"`
	To                       json.RawMessage `json:"to"`
	ToUser                   json.RawMessage `json:"toUser"`
}

type EntityAction struct {
	EntityActionDate         string `json:"entityActionDate"`
	EntityActionName         string `json:"entityActionName"`
	EntityActionResponseCode int    `json:"entityActionResponseCode"`
	EntityActionResponseText string `json:"entityActionResponseText"`
	EntityActionState        string `json:"entityActionState"`
}

type EntityAvailableAction struct {
	EntityActionName  string `json:"entityActionName"`
	EntityActionParam string `json:"entityActionParam"`
}

type EntityInfo struct {
	CustomerId        string `json:"customerId"`
	EntityActionState string `json:"entityActionState"`
	EntityCreated     string `json:"entityCreated"`
	EntityId          string `json:"entityId"`
	EntityUpdated     string `json:"entityUpdated"`
	Saas              string `json:"saas"`
	SaasEntityType    string `json:"saasEntityType"`
}

type EntitySecurityResult struct {
	Ap                  json.RawMessage `json:"ap"`
	Av                  json.RawMessage `json:"av"`
	ClicktimeProtection json.RawMessage `json:"clicktimeProtection"`
	CombinedVerdict     json.RawMessage `json:"combinedVerdict"`
	Dlp                 json.RawMessage `json:"dlp"`
	ShadowIt            json.RawMessage `json:"shadowIt"`
}

type EventAction struct {
	ActionType      string `json:"actionType"`
	CreateTime      string `json:"createTime"`
	RelatedEntityId string `json:"relatedEntityId"`
}

type EventActionRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type EventActionRequestData struct {
	EventActionName  string          `json:"eventActionName"`
	EventActionParam string          `json:"eventActionParam"`
	EventIds         json.RawMessage `json:"eventIds"`
	Scope            string          `json:"scope"`
}

type EventActionResponse struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type EventActionTask struct {
	EntityId string `json:"entityId"`
	EventId  string `json:"eventId"`
	TaskId   string `json:"taskId"`
}

type EventEntity struct {
	Actions               json.RawMessage `json:"actions"`
	AdditionalData        json.RawMessage `json:"additionalData"`
	AvailableEventActions json.RawMessage `json:"availableEventActions"`
	ConfidenceIndicator   string          `json:"confidenceIndicator"`
	CustomerId            string          `json:"customerId"`
	Data                  string          `json:"data"`
	Description           string          `json:"description"`
	EntityId              string          `json:"entityId"`
	EventCreated          string          `json:"eventCreated"`
	EventId               string          `json:"eventId"`
	Saas                  string          `json:"saas"`
	Severity              string          `json:"severity"`
	State                 string          `json:"state"`
	Type                  string          `json:"type"`
}

type EventQuery struct {
	RequestData json.RawMessage `json:"requestData"`
}

type EventQueryRequestData struct {
	ConfidenceIndicator string          `json:"confidenceIndicator"`
	Description         string          `json:"description"`
	EndDate             string          `json:"endDate"`
	EventIds            json.RawMessage `json:"eventIds"`
	EventStates         json.RawMessage `json:"eventStates"`
	EventTypes          json.RawMessage `json:"eventTypes"`
	Saas                json.RawMessage `json:"saas"`
	Scopes              json.RawMessage `json:"scopes"`
	ScrollId            string          `json:"scrollId"`
	Severities          json.RawMessage `json:"severities"`
	StartDate           string          `json:"startDate"`
}

type EventResponse struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type HTTPValidationError struct {
	Detail json.RawMessage `json:"detail"`
}

type HealthCheckResponse struct {
	Ok bool `json:"ok"`
}

type LicenseInput struct {
	AddonIdList      json.RawMessage `json:"addonIdList"`
	LicenseCodeName  string          `json:"licenseCodeName"`
	MaxLicensedUsers int             `json:"maxLicensedUsers"`
}

type LicenseList struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type LicenseRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type ListTenantsInput struct {
	MSPId    int    `json:"MSPId"`
	ScrollId string `json:"scrollId"`
}

type ListTenantsRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type ListUsagesInput struct {
	ScrollId string `json:"scrollId"`
}

type ListUsagesRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type ListUsersInput struct {
	MSPId    int    `json:"MSPId"`
	ScrollId string `json:"scrollId"`
}

type ListUsersRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type MSP struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type MSPDetails struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type MSPInput struct {
	Name string `json:"name"`
}

type MSPList struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type MSPRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type Package struct {
	CodeName    string `json:"codeName"`
	DisplayName string `json:"displayName"`
	Id          int    `json:"id"`
}

type PortalLicense struct {
	Addons           json.RawMessage `json:"addons"`
	License          json.RawMessage `json:"license"`
	MaxLicensedUsers int             `json:"maxLicensedUsers"`
	TenantDomain     string          `json:"tenantDomain"`
	TenantId         int             `json:"tenantId"`
}

type PortalLicenseDetails struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type ResponseEnvelope struct {
	AdditionalText string `json:"additionalText"`
	RecordsNumber  int    `json:"recordsNumber"`
	RequestId      string `json:"requestId"`
	ResponseCode   int    `json:"responseCode"`
	ResponseText   string `json:"responseText"`
	ScrollId       string `json:"scrollId"`
}

type SaasEntity struct {
	EntityActions          json.RawMessage `json:"entityActions"`
	EntityAvailableActions json.RawMessage `json:"entityAvailableActions"`
	EntityInfo             string          `json:"entityInfo"`
	EntityPayload          string          `json:"entityPayload"`
	EntitySecurityResult   string          `json:"entitySecurityResult"`
}

type SaasEntityActionRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type SaasEntityActionRequestData struct {
	EntityActionName  string          `json:"entityActionName"`
	EntityActionParam string          `json:"entityActionParam"`
	EntityIds         json.RawMessage `json:"entityIds"`
	EntityType        string          `json:"entityType"`
	Scope             string          `json:"scope"`
}

type SaasEntityActionResponse struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type SaasEntityActionTask struct {
	EntityId string `json:"entityId"`
	TaskId   string `json:"taskId"`
}

type SaasEntityExtendedFilter struct {
	SaasAttrName  string `json:"saasAttrName"`
	SaasAttrOp    string `json:"saasAttrOp"`
	SaasAttrValue string `json:"saasAttrValue"`
}

type SaasEntityFilter struct {
	EndDate    string `json:"endDate"`
	Saas       string `json:"saas"`
	SaasEntity string `json:"saasEntity"`
	StartDate  string `json:"startDate"`
}

type SaasEntityQuery struct {
	RequestData json.RawMessage `json:"requestData"`
}

type SaasEntityQueryRequestData struct {
	EntityExtendedFilter json.RawMessage `json:"entityExtendedFilter"`
	EntityFilter         json.RawMessage `json:"entityFilter"`
	Scopes               json.RawMessage `json:"scopes"`
	ScrollId             string          `json:"scrollId"`
}

type SaasEntityResponse struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type SaasUserPayload struct {
	EntityId   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Mail       string `json:"mail"`
}

type ScopesResponse struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type SectoolResult struct {
	EntityId                 string          `json:"entityId"`
	EntityType               string          `json:"entityType"`
	Payload                  json.RawMessage `json:"payload"`
	Score                    string          `json:"score"`
	SecurityResultEntityId   string          `json:"securityResultEntityId"`
	SecurityResultEntityType string          `json:"securityResultEntityType"`
	StatusCode               string          `json:"statusCode"`
	StatusDescription        string          `json:"statusDescription"`
	Verdict                  string          `json:"verdict"`
}

type Tenant struct {
	MSP               json.RawMessage `json:"MSP"`
	Addons            json.RawMessage `json:"addons"`
	DeploymentMode    string          `json:"deploymentMode"`
	Domain            string          `json:"domain"`
	Id                int             `json:"id"`
	MaxLicensedUsers  int             `json:"maxLicensedUsers"`
	Package           json.RawMessage `json:"package"`
	PocDateExpiration string          `json:"pocDateExpiration"`
	PocDateStart      string          `json:"pocDateStart"`
	Status            json.RawMessage `json:"status"`
	Users             int             `json:"users"`
}

type TenantDetails struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type TenantInput struct {
	MSPId        int    `json:"MSPId"`
	AdminEmail   string `json:"adminEmail"`
	AdminName    string `json:"adminName"`
	CompanyName  string `json:"companyName"`
	Phone        string `json:"phone"`
	TenantName   string `json:"tenantName"`
	TenantRegion string `json:"tenantRegion"`
}

type TenantList struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type TenantRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type TenantStatus struct {
	Description string `json:"description"`
	StatusCode  string `json:"statusCode"`
}

type Usage struct {
	MSPName         string  `json:"MSPName"`
	Cost            float64 `json:"cost"`
	DailyPrice      float64 `json:"dailyPrice"`
	Day             string  `json:"day"`
	LicenseCodeName string  `json:"licenseCodeName"`
	TenantDomain    string  `json:"tenantDomain"`
	Users           int     `json:"users"`
}

type UsageList struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type User struct {
	MSPId                int    `json:"MSPId"`
	MSPName              string `json:"MSPName"`
	DirectLogin          bool   `json:"directLogin"`
	Email                string `json:"email"`
	FirstName            string `json:"firstName"`
	Id                   int    `json:"id"`
	LastName             string `json:"lastName"`
	ReceiveWeeklyReports bool   `json:"receiveWeeklyReports"`
	Role                 string `json:"role"`
	SamlLogin            bool   `json:"samlLogin"`
	SendAlerts           bool   `json:"sendAlerts"`
	ViewPrivateData      bool   `json:"viewPrivateData"`
}

type UserDetails struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type UserInput struct {
	MSPId                int    `json:"MSPId"`
	DirectLogin          bool   `json:"directLogin"`
	Email                string `json:"email"`
	FirstName            string `json:"firstName"`
	LastName             string `json:"lastName"`
	ReceiveWeeklyReports bool   `json:"receiveWeeklyReports"`
	Role                 string `json:"role"`
	SamlLogin            bool   `json:"samlLogin"`
	SendAlerts           bool   `json:"sendAlerts"`
	ViewPrivateData      bool   `json:"viewPrivateData"`
}

type UserList struct {
	ResponseData     json.RawMessage `json:"responseData"`
	ResponseEnvelope json.RawMessage `json:"responseEnvelope"`
}

type UserRequest struct {
	RequestData json.RawMessage `json:"requestData"`
}

type ValidationError struct {
	Loc  json.RawMessage `json:"loc"`
	Msg  string          `json:"msg"`
	Type string          `json:"type"`
}
