// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL       string            `toml:"base_url"`
	AuthHeaderVal string            `toml:"auth_header"`
	Headers       map[string]string `toml:"headers,omitempty"`
	AuthSource    string            `toml:"-"`
	AccessToken   string            `toml:"access_token"`
	RefreshToken  string            `toml:"refresh_token"`
	TokenExpiry   time.Time         `toml:"token_expiry"`
	ClientID      string            `toml:"client_id"`
	ClientSecret  string            `toml:"client_secret"`
	Path          string            `toml:"-"`
	envOverrides  map[string]bool   `toml:"-"`
	fileConfig    *Config           `toml:"-"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://quickbooks.api.intuit.com/v3/company/YOUR_REALM_ID",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("QUICKBOOKS_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "quickbooks-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	cfg.snapshotFileConfig()

	// Env var overrides
	// The refresh inputs, so a container can be seeded entirely from the
	// environment. QUICKBOOKS_ACCESS_TOKEN below stays the short-circuit for a
	// hand-supplied token; these three are what the client refreshes with.
	// Every one is markEnvOverride'd so an env-supplied secret is never written
	// back to the file (#268 semantics).
	if v := os.Getenv("QUICKBOOKS_CLIENT_ID"); v != "" {
		cfg.ClientID = v
		cfg.markEnvOverride("ClientID")
	}
	if v := os.Getenv("QUICKBOOKS_CLIENT_SECRET"); v != "" {
		cfg.ClientSecret = v
		cfg.markEnvOverride("ClientSecret")
	}
	if v := os.Getenv("QUICKBOOKS_REFRESH_TOKEN"); v != "" {
		cfg.RefreshToken = v
		cfg.markEnvOverride("RefreshToken")
		if cfg.AuthSource == "" {
			cfg.AuthSource = "env:QUICKBOOKS_REFRESH_TOKEN"
		}
	}
	if v := os.Getenv("QUICKBOOKS_ACCESS_TOKEN"); v != "" {
		cfg.AccessToken = v
		cfg.markEnvOverride("AccessToken")
		cfg.AuthSource = "env:QUICKBOOKS_ACCESS_TOKEN"
	}

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "" || cfg.AccessToken != "") {
		cfg.AuthSource = "config"
	}

	// Soft agentcookie integration: if the agentcookie daemon manages this
	// CLI's secrets, it writes a marker file alongside the config file. When
	// the marker is present AND credentials came from the config (not from a
	// direct env var override that wins above), upgrade AuthSource to
	// "agentcookie" so doctor / auth-status can surface the bus state. When
	// the marker is absent, behavior is identical to pre-agentcookie: no
	// import, no network, no error. agentcookie itself is never imported
	// here — the contract is purely on-disk.
	if cfg.AuthSource == "config" {
		marker := filepath.Join(filepath.Dir(cfg.Path), ".agentcookie-managed")
		if _, err := os.Stat(marker); err == nil {
			cfg.AuthSource = "agentcookie"
		}
	}

	// Base URL override (used by printing-press verify to point at mock/test servers).
	// Precedence: explicit QUICKBOOKS_BASE_URL wins; else the QUICKBOOKS_REALM_ID
	// convenience composes the company-scoped base from the environment host and
	// the realm id, so users set just a realm + environment instead of building the
	// full /v3/company/<realmId> URL by hand. This mirrors the official Intuit MCP
	// env-var convention (QUICKBOOKS_REALM_ID + QUICKBOOKS_ENVIRONMENT).
	if v := os.Getenv("QUICKBOOKS_BASE_URL"); v != "" {
		cfg.BaseURL = v
	} else if realm := strings.TrimSpace(os.Getenv("QUICKBOOKS_REALM_ID")); realm != "" {
		host := "https://quickbooks.api.intuit.com"
		switch strings.ToLower(strings.TrimSpace(os.Getenv("QUICKBOOKS_ENVIRONMENT"))) {
		case "sandbox", "sbx":
			host = "https://sandbox-quickbooks.api.intuit.com"
		}
		cfg.BaseURL = fmt.Sprintf("%s/v3/company/%s", host, realm)
	}
	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	// Env-var token wins over file-stored AccessToken (env > config convention).
	if c.AccessToken != "" {
		if c.AuthSource == "" {
			c.AuthSource = "env:QUICKBOOKS_ACCESS_TOKEN"
		}
		return applyAuthFormat("Bearer {token}", map[string]string{
			"access_token":            c.AccessToken,
			"QUICKBOOKS_ACCESS_TOKEN": c.AccessToken,
			"token":                   c.AccessToken,
		})
	}
	if c.AccessToken != "" {
		if c.AuthSource == "" || strings.HasPrefix(c.AuthSource, "env:") {
			c.AuthSource = "oauth2"
		}
		return applyAuthFormat("Bearer {token}", map[string]string{"access_token": c.AccessToken, "token": c.AccessToken})
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	// The minted material persists deliberately: the access token, the expiry,
	// and the refresh token, because Intuit ROTATES refresh tokens and
	// invalidates the previous value, so a restart that fell back to the
	// original env seed would be locked out. Deleting those three markers is
	// what makes the minted values reach the file even when the seed came from
	// the environment.
	//
	// The ClientID and ClientSecret markers are deliberately NOT deleted.
	// Deleting them defeated configForSave's env guard and wrote an
	// env-supplied client secret to disk in cleartext, which is the same
	// defect immybot's save-tokens-keeps-env-credential-markers hand-fix
	// records.
	delete(c.envOverrides, "AccessToken")
	delete(c.envOverrides, "RefreshToken")
	delete(c.envOverrides, "TokenExpiry")
	c.updateFileConfigField("ClientID")
	c.updateFileConfigField("ClientSecret")
	c.updateFileConfigField("AccessToken")
	c.updateFileConfigField("RefreshToken")
	c.updateFileConfigField("TokenExpiry")
	return c.save()
}

func (c *Config) ClearTokens() error {
	// AuthHeader() falls back to the env-var-derived fields when AuthHeaderVal
	// and AccessToken are empty, so dropping the working credential requires
	// zeroing every emitted credential field, not just the OAuth trio.
	// ClientID/ClientSecret persist to disk via SaveTokens for the oauth2
	// and oauth2-cc flows, so logout must wipe them too; otherwise
	// `auth login` can re-mint a new access token unattended.
	c.AuthHeaderVal = ""
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	delete(c.envOverrides, "AuthHeaderVal")
	delete(c.envOverrides, "AccessToken")
	delete(c.envOverrides, "RefreshToken")
	delete(c.envOverrides, "TokenExpiry")
	delete(c.envOverrides, "ClientID")
	delete(c.envOverrides, "ClientSecret")
	c.updateFileConfigField("AuthHeaderVal")
	c.updateFileConfigField("AccessToken")
	c.updateFileConfigField("RefreshToken")
	c.updateFileConfigField("TokenExpiry")
	c.updateFileConfigField("ClientID")
	c.updateFileConfigField("ClientSecret")
	return c.save()
}

func (c *Config) markEnvOverride(field string) {
	if c.envOverrides == nil {
		c.envOverrides = map[string]bool{}
	}
	c.envOverrides[field] = true
}

// cloneStringMap returns an independent copy of m (nil stays nil). The fileConfig
// snapshot must not share reference-type map fields (such as Headers) with the
// live config, or a later mutation to one would silently track in the other.
func cloneStringMap(m map[string]string) map[string]string {
	if m == nil {
		return nil
	}
	out := make(map[string]string, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

func (c *Config) snapshotFileConfig() {
	snapshot := *c
	snapshot.envOverrides = nil
	snapshot.fileConfig = nil
	// *c is a shallow copy: map fields are reference types, so the snapshot would
	// share them with c and silently track later mutations, defeating the
	// isolation this snapshot exists to provide. Clone them.
	snapshot.Headers = cloneStringMap(c.Headers)
	c.fileConfig = &snapshot
}

func (c *Config) configForSave() Config {
	out := *c
	if c.fileConfig != nil {
		if c.envOverrides["AccessToken"] {
			out.AccessToken = c.fileConfig.AccessToken
		}
		if c.envOverrides["ClientID"] {
			out.ClientID = c.fileConfig.ClientID
		}
		if c.envOverrides["ClientSecret"] {
			out.ClientSecret = c.fileConfig.ClientSecret
		}
		if c.envOverrides["RefreshToken"] {
			out.RefreshToken = c.fileConfig.RefreshToken
		}
	}
	out.envOverrides = nil
	out.fileConfig = nil
	return out
}

func (c *Config) updateFileConfigField(field string) {
	if c.fileConfig == nil || c.envOverrides[field] {
		return
	}
	switch field {
	case "AuthHeaderVal":
		c.fileConfig.AuthHeaderVal = c.AuthHeaderVal
	case "AccessToken":
		c.fileConfig.AccessToken = c.AccessToken
	case "RefreshToken":
		c.fileConfig.RefreshToken = c.RefreshToken
	case "TokenExpiry":
		c.fileConfig.TokenExpiry = c.TokenExpiry
	case "ClientID":
		c.fileConfig.ClientID = c.ClientID
	case "ClientSecret":
		c.fileConfig.ClientSecret = c.ClientSecret
	}
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	persisted := c.configForSave()
	data, err := toml.Marshal(persisted)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	if err := os.WriteFile(c.Path, data, 0o600); err != nil {
		return err
	}
	c.fileConfig = &persisted
	c.fileConfig.envOverrides = nil
	c.fileConfig.fileConfig = nil
	// persisted shares its map fields with c (configForSave shallow-copies *c),
	// so isolate the stored fileConfig the same way snapshotFileConfig does;
	// otherwise later mutations to c's maps leak into the on-disk snapshot.
	c.fileConfig.Headers = cloneStringMap(c.fileConfig.Headers)
	return nil
}

// Ensure strings import is used
var _ = strings.ReplaceAll

// DefaultTokenURL is Intuit's production token endpoint.
const DefaultTokenURL = "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"

// tokenRefreshSkew re-mints slightly early so a token cannot expire between
// the check and the request it authorizes.
const tokenRefreshSkew = 2 * time.Minute

// CanMintToken reports whether the refresh inputs are all present, whatever
// their source: environment in a container, config file on a laptop.
func (c *Config) CanMintToken() bool {
	return c != nil && c.ClientID != "" && c.ClientSecret != "" && c.RefreshToken != ""
}

// TokenNeedsRefresh reports whether the cached access token is missing or too
// close to expiry to trust.
//
// Nothing consulted TokenExpiry before this. An Intuit access token lives one
// hour, `auth refresh` existed but nothing called it, so the connector worked
// for an hour per manual refresh. Same defect cipp had.
func (c *Config) TokenNeedsRefresh() bool {
	if c.AuthHeaderVal != "" {
		// A hand-supplied header is not ours to refresh.
		return false
	}
	if envAccessTokenSupplied() {
		// An operator who pins QUICKBOOKS_ACCESS_TOKEN gets exactly that token.
		return false
	}
	if c.AccessToken == "" {
		return true
	}
	if c.TokenExpiry.IsZero() {
		// Cached by a build that recorded no expiry; do not churn mints.
		return false
	}
	return time.Now().After(c.TokenExpiry.Add(-tokenRefreshSkew))
}

func envAccessTokenSupplied() bool {
	return strings.TrimSpace(os.Getenv("QUICKBOOKS_ACCESS_TOKEN")) != ""
}

// EffectiveTokenURL returns the configured token endpoint or Intuit's default.
func EffectiveTokenURL() string {
	if v := strings.TrimSpace(os.Getenv("QUICKBOOKS_TOKEN_URL")); v != "" {
		return v
	}
	return DefaultTokenURL
}
