// Copyright 2026 Abhi Saini and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"immybot-pp-cli/internal/cli"
	"immybot-pp-cli/internal/client"
	"immybot-pp-cli/internal/cliutil"
	"immybot-pp-cli/internal/config"
	"immybot-pp-cli/internal/learn"
	"immybot-pp-cli/internal/mcp/bound"
	"immybot-pp-cli/internal/mcp/cobratree"
	"immybot-pp-cli/internal/platform"
	"immybot-pp-cli/internal/store"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	installFreshTenantGate(s)
	installReadOnlyGate(s)
	// Code-orchestration mode — the full surface is covered by registry tools
	// (<api>_search, <api>_get, and <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Intent tools — higher-level compositions declared in the spec or lifted from recipes.
	RegisterIntents(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='access'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName         string
	WireName           string
	Location           string
	BodyPath           []string
	Format             string
	QueryArray         bool
	QueryStyle         string
	QueryExplode       bool
	RequestContentType string
	Default            string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

func mcpPathValue(v any) string {
	return cliutil.EscapePathParam(formatMCPParamValue(v))
}
func appendMCPArrayQueryParam(path, name string, value any, style string, explode bool) string {
	var values []string
	switch typed := value.(type) {
	case []any:
		values = make([]string, 0, len(typed))
		for _, item := range typed {
			values = append(values, formatMCPParamValue(item))
		}
	case []string:
		values = typed
	default:
		raw := formatMCPParamValue(value)
		var decoded []any
		if json.Unmarshal([]byte(raw), &decoded) == nil {
			for _, item := range decoded {
				values = append(values, formatMCPParamValue(item))
			}
		} else {
			for _, item := range strings.Split(raw, ",") {
				if item = strings.TrimSpace(item); item != "" {
					values = append(values, item)
				}
			}
		}
	}
	if len(values) == 0 {
		return path
	}

	query := url.Values{}
	switch style {
	case "spaceDelimited":
		query.Set(name, strings.Join(values, " "))
	case "pipeDelimited":
		query.Set(name, strings.Join(values, "|"))
	case "form":
		if explode {
			for _, item := range values {
				query.Add(name, item)
			}
		} else {
			query.Set(name, strings.Join(values, ","))
		}
	default:
		query.Set(name, formatMCPParamValue(value))
	}

	separator := "?"
	if strings.Contains(path, "?") {
		separator = "&"
	}
	return path + separator + query.Encode()
}
func mcpMultipartFieldValue(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	if data, err := json.Marshal(v); err == nil {
		return string(data)
	}
	return fmt.Sprintf("%v", v)
}
func setNestedBodyArg(body map[string]any, path []string, value any) {
	if len(path) == 0 {
		return
	}
	if len(path) == 1 {
		body[path[0]] = value
		return
	}
	current := body
	for _, key := range path[:len(path)-1] {
		next, ok := current[key].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[key] = next
		}
		current = next
	}
	current[path[len(path)-1]] = value
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, platformSession, err := newMCPClient(ctx)
		if err != nil {
			return mcpToolError(err.Error()), nil
		}
		if platformSession != nil {
			defer platformSession.ZeroCredentials()
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()
		if err := cli.AdoptMCPOutputSemantics(platformSession, args); err != nil {
			return mcpToolError(err.Error()), nil
		}

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcpToolError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcpToolError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		multipartFields := make(map[string]string)
		multipartFileFields := make(map[string]string)
		multipart := false
		// bodyJSONOverride holds an opaque body for endpoints whose request
		// schema is a oneOf/anyOf and was wired with a single body_json input.
		// When set, it replaces the bodyArgs map for POST/PUT/PATCH.
		var bodyJSONOverride json.RawMessage
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			if strings.EqualFold(binding.RequestContentType, "multipart/form-data") {
				multipart = true
			}
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "header":
				if headers == nil {
					headers = map[string]string{}
				}
				headers[binding.WireName] = formatMCPParamValue(v)
			case "body":
				if len(binding.BodyPath) > 0 {
					setNestedBodyArg(bodyArgs, binding.BodyPath, v)
				} else {
					bodyArgs[binding.WireName] = v
				}
				if multipart {
					if strings.EqualFold(binding.Format, "binary") {
						multipartFileFields[binding.WireName] = fmt.Sprintf("%v", v)
					} else {
						multipartFields[binding.WireName] = mcpMultipartFieldValue(v)
					}
				}
			case "body_json":
				if s, ok := v.(string); ok && s != "" {
					var parsed any
					if err := json.Unmarshal([]byte(s), &parsed); err != nil {
						return mcpToolError("body_json must be a valid JSON object: " + err.Error()), nil
					}
					if _, isMap := parsed.(map[string]any); !isMap {
						return mcpToolError(fmt.Sprintf("body_json must be a JSON object, got JSON %T", parsed)), nil
					}
					bodyJSONOverride = json.RawMessage(s)
				}
			default:
				if binding.QueryArray {
					path = appendMCPArrayQueryParam(path, binding.WireName, v, binding.QueryStyle, binding.QueryExplode)
				} else {
					params[binding.WireName] = formatMCPParamValue(v)
				}
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
				if multipart {
					multipartFields[k] = mcpMultipartFieldValue(v)
				}
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				if readOnly {
					data, err = c.GetWithHeaders(ctx, path, params, headers)
				} else {
					data, err = c.GetMutatingWithHeaders(ctx, path, params, headers)
				}
				break
			}
			if readOnly {
				data, err = c.Get(ctx, path, params)
			} else {
				data, err = c.GetMutating(ctx, path, params)
			}
		case "POST":
			if multipart {
				if len(headers) > 0 {
					data, _, err = c.PostMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
					break
				}
				data, _, err = c.PostMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
				break
			}
			if len(bodyJSONOverride) > 0 {
				if len(headers) > 0 {
					if readOnly {
						data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					} else {
						data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					}
					break
				}
				if readOnly {
					data, _, err = c.PostQueryWithParams(ctx, path, params, bodyJSONOverride)
				} else {
					data, _, err = c.PostWithParams(ctx, path, params, bodyJSONOverride)
				}
				break
			}
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if multipart {
				if len(headers) > 0 {
					if readOnly {
						data, _, err = c.PutQueryMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
						break
					}
					data, _, err = c.PutMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
					break
				}
				if readOnly {
					data, _, err = c.PutQueryMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
					break
				}
				data, _, err = c.PutMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
				break
			}
			if len(bodyJSONOverride) > 0 {
				if len(headers) > 0 {
					if readOnly {
						data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					} else {
						data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					}
					break
				}
				if readOnly {
					data, _, err = c.PutQueryWithParams(ctx, path, params, bodyJSONOverride)
				} else {
					data, _, err = c.PutWithParams(ctx, path, params, bodyJSONOverride)
				}
				break
			}
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PutQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
			}
		case "PATCH":
			if multipart {
				if len(headers) > 0 {
					if readOnly {
						data, _, err = c.PatchQueryMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
						break
					}
					data, _, err = c.PatchMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
					break
				}
				if readOnly {
					data, _, err = c.PatchQueryMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
					break
				}
				data, _, err = c.PatchMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
				break
			}
			if len(bodyJSONOverride) > 0 {
				if len(headers) > 0 {
					if readOnly {
						data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					} else {
						data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					}
					break
				}
				if readOnly {
					data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyJSONOverride)
				} else {
					data, _, err = c.PatchWithParams(ctx, path, params, bodyJSONOverride)
				}
				break
			}
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
			}
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcpToolError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcpToolTextWithPlatform("already exists (no-op)", platformSession), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcpToolError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Run 'immybot-cli auth login' to mint a token (or 'immybot-cli auth status' to see what is loaded)." +
					"\n      See API docs: https://www.immy.bot" +
					"\n      Register an app in Microsoft Entra ID, create a client secret, then in ImmyBot go to Show More > People > New and paste the Enterprise App object ID into \"AD External ID\". Set IMMYBOT_SUBDOMAIN, IMMYBOT_TENANT_ID, IMMYBOT_CLIENT_ID and IMMYBOT_CLIENT_SECRET." +
					"\n      Run 'immybot-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcpToolError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Run 'immybot-cli auth login' to mint a token (or 'immybot-cli auth status' to see what is loaded)." +
					"\n      See API docs: https://www.immy.bot" +
					"\n      Register an app in Microsoft Entra ID, create a client secret, then in ImmyBot go to Show More > People > New and paste the Enterprise App object ID into \"AD External ID\". Set IMMYBOT_SUBDOMAIN, IMMYBOT_TENANT_ID, IMMYBOT_CLIENT_ID and IMMYBOT_CLIENT_SECRET." +
					"\n      Run 'immybot-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcpToolError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource. Check that they have the required permissions and match the API's expected auth scheme." +
					"\n      Run 'immybot-cli auth login' to mint a token (or 'immybot-cli auth status' to see what is loaded)." +
					"\n      See API docs: https://www.immy.bot" +
					"\n      Register an app in Microsoft Entra ID, create a client secret, then in ImmyBot go to Show More > People > New and paste the Enterprise App object ID into \"AD External ID\". Set IMMYBOT_SUBDOMAIN, IMMYBOT_TENANT_ID, IMMYBOT_CLIENT_ID and IMMYBOT_CLIENT_SECRET." +
					"\n      Run 'immybot-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcpToolTextWithPlatform("already deleted (no-op)", platformSession), nil
				}
				return mcpToolError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcpToolError("rate limited: " + msg), nil
			default:
				return mcpToolError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcpToolError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcpToolError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			result := string(out)
			if platformSession != nil {
				result = bound.WithMetadata(result, platformSession.OutputMetadata())
			}
			return mcplib.NewToolResultText(result), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultTextWithPlatform(method, data, pageConfig, mcpCursor, platformSession), nil
		}
		return mcpToolResultTextWithPlatform(method, data, platformSession), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcpToolResultTextWithPlatform(method, data, nil)
}

func mcpToolTextWithPlatform(result string, platformSession *platform.Session) *mcplib.CallToolResult {
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func mcpToolResultTextWithPlatform(method string, data json.RawMessage, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointResponse(method, data)
	return mcpToolTextWithPlatform(result, platformSession)
}

// mcpToolError keeps provider-controlled typed endpoint errors within the MCP
// text-result budget just like successful endpoint results.
func mcpToolError(message string) *mcplib.CallToolResult {
	return mcplib.NewToolResultError(bound.Text(message))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcpToolPageResultTextWithPlatform(method, data, pageConfig, cursor, nil)
}

func mcpToolPageResultTextWithPlatform(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	})
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func newMCPClient(ctx context.Context) (*client.Client, *platform.Session, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, nil, err
	}
	c := newMCPClientFromConfig(cfg)
	session, err := cli.BindMCPClient(ctx, c)
	if err != nil {
		return nil, nil, err
	}
	return c, session, nil
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(cfg *config.Config) *client.Client {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c
}

func mcpDBPath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "data.db"), nil
}

type mcpStoreStatusKind string

const (
	mcpStoreStatusEmpty mcpStoreStatusKind = "empty"
	mcpStoreStatusReady mcpStoreStatusKind = "ready"
)

func openMCPReadOnlyStore(path string) (*store.Store, *mcplib.CallToolResult) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil, mcplib.NewToolResultError(mcpMissingStoreMessage(path))
		}
		return nil, mcplib.NewToolResultError(fmt.Sprintf("checking local data store %s: %v", path, err))
	}
	db, err := store.OpenReadOnly(path)
	if err != nil {
		return nil, mcplib.NewToolResultError(fmt.Sprintf("opening local data store %s: %v. Run immybot-cli sync to refresh the store, or use live endpoint MCP tools for unsynced data.", path, err))
	}
	return db, nil
}

func mcpMissingStoreMessage(path string) string {
	return fmt.Sprintf("No local data store found at %s. Run immybot-cli sync before using MCP search/sql, or use live endpoint MCP tools for unsynced data.", path)
}

func mcpStoreStatus(db *store.Store) (mcpStoreStatusKind, error) {
	status, err := db.Status()
	if err != nil {
		return "", err
	}
	if len(status) == 0 {
		return mcpStoreStatusEmpty, nil
	}
	return mcpStoreStatusReady, nil
}

func mcpEmptyStoreNextStep() string {
	return "Run immybot-cli sync to populate the local SQLite store before using MCP search/sql."
}

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSearchEnvelope(results, storeStatus))
}

func mcpSearchEnvelope(results []json.RawMessage, storeStatus mcpStoreStatusKind) map[string]any {
	if results == nil {
		results = []json.RawMessage{}
	}
	out := map[string]any{
		"count":        len(results),
		"results":      results,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if len(results) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "No local search matches. Try a broader query, a lower-specificity FTS expression, or sync again if data may be stale."
		}
	}
	return out
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	rows, err := db.DB().QueryContext(ctx, query)
	if err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSQLEnvelope(results, cols, storeStatus))
}

func mcpSQLEnvelope(rows []map[string]any, columns []string, storeStatus mcpStoreStatusKind) map[string]any {
	if rows == nil {
		rows = []map[string]any{}
	}
	out := map[string]any{
		"count":        len(rows),
		"columns":      columns,
		"rows":         rows,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if len(rows) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "The read-only SQL query returned no rows. Check resource_type filters, json_extract paths, or run sync again if data may be stale."
		}
	}
	return out
}

func mcpSQLQueryError(err error) string {
	msg := err.Error()
	if strings.Contains(strings.ToLower(msg), "no such table") {
		return fmt.Sprintf("query failed: %v. Synced records live in resources(resource_type, id, data), not one SQL table per resource. Filter by resource_type, for example resource_type='access', and read JSON fields with json_extract(data,'$.field').", err)
	}
	return fmt.Sprintf("query failed: %v", err)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "immybot",
		"description": "Every ImmyBot endpoint typed, plus a local SQLite mirror that answers the cross-tenant questions the web UI cannot.",
		"archetype":   "project-management",
		"tool_count":  550,
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion immybot-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":      "IMMYBOT_SUBDOMAIN",
					"kind":      "auth_flow_input",
					"required":  true,
					"sensitive": false,
					// Must match cli/agent_context.go: this handler and the CLI
					// agent-context command are the same contract on two
					// surfaces, and SUBDOMAIN is the one whose absence breaks
					// the OAuth scope (see the doctor/agent-context handfixes).
					"description": "ImmyBot instance subdomain (the \"acme\" in acme.immy.bot). Derives the OAuth scope.",
				},
				{
					"name":        "IMMYBOT_TENANT_ID",
					"kind":        "auth_flow_input",
					"required":    true,
					"sensitive":   false,
					"description": "Microsoft Entra directory (tenant) ID that issues the token.",
				},
				{
					"name":        "IMMYBOT_CLIENT_ID",
					"kind":        "auth_flow_input",
					"required":    true,
					"sensitive":   false,
					"description": "Application (client) ID of the Entra app registration.",
				},
				{
					"name":        "IMMYBOT_CLIENT_SECRET",
					"kind":        "auth_flow_input",
					"required":    true,
					"sensitive":   true,
					"description": "Client secret paired with IMMYBOT_CLIENT_ID, from the Entra app registration.",
				},
			},
			"docs_url":     "https://www.immy.bot",
			"instructions": "Register an app in Microsoft Entra ID, create a client secret, then in ImmyBot go to Show More > People > New and paste the Enterprise App object ID into \"AD External ID\". Set IMMYBOT_SUBDOMAIN, IMMYBOT_TENANT_ID, IMMYBOT_CLIENT_ID and IMMYBOT_CLIENT_SECRET.",
		},
		"resources": []map[string]any{
			{
				"name":        "access",
				"description": "Manage access",
				"endpoints":   []string{"create-delete-azure-tenant-auth-details", "create-request", "create-update-azure-tenant-auth-details", "get-get-azure-tenant-auth-details-by-azure-tenant-principal-id", "get-get-ip-addresses", "get-me-permissions-by-permission-type-tenants", "list"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "application-locks",
				"description": "Manage application locks",
				"endpoints":   []string{"create-request-cancellation", "get-realtime-event-stream", "list"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "application-logs",
				"description": "Manage application logs",
				"endpoints":   []string{"create-source-context", "create-source-context-clear", "create-source-context-clear-all", "create-streaming", "get-source-contexts"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "audits",
				"description": "Manage audits",
				"endpoints":   []string{"get-global-dx", "get-local-dx"},
				"syncable":    true,
			},
			{
				"name":        "azure",
				"description": "Manage azure",
				"endpoints":   []string{"create-disambiguate-tenant-type", "create-preconsent-customer-tenants", "create-sync-details-from-tenants", "create-sync-users-from-tenants", "create-tenant-consented", "get-app-registration-options", "get-partner-tenant-customers-by-partner-principal-id", "get-partner-tenant-infos"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "azure-errors",
				"description": "Manage azure errors",
				"endpoints":   []string{"get-dx", "get-for-tenant-by-tenant-principal-id-dx"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "billing",
				"description": "Manage billing",
				"endpoints":   []string{"create-cancel-subscription", "create-information", "create-reactivate-subscription", "create-update-addon", "create-update-subscription", "get-credit-cards", "get-download-invoice", "get-feature-usage-counts", "get-information", "get-platform-details", "get-product-catalog", "get-product-catalog-items", "get-subscription-details"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "brandings",
				"description": "Manage brandings",
				"endpoints":   []string{"create", "create-global-default-by-id", "create-send-test-email", "create-validate-time-format-by-time-format", "delete-by-id", "get-by-id", "get-support", "list", "update-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "change-requests",
				"description": "Manage change requests",
				"endpoints":   []string{"delete-by-id", "get-dx", "get-open-count"},
				"syncable":    true,
				"writable":    true,
			},
			{
				"name":        "change-requests.approve",
				"description": "Manage approve",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "change-requests.comment",
				"description": "Manage comment",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "change-requests.deny",
				"description": "Manage deny",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "change-requests.require-changes",
				"description": "Manage require changes",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "chocolatey",
				"description": "Manage chocolatey",
				"endpoints":   []string{"get-find-packages-by-id", "get-search"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "computers",
				"description": "Manage computers",
				"endpoints":   []string{"create-add-tags", "create-bulk-delete", "create-change-tenant", "create-remove-tags", "create-restore", "create-set-excluded-from-user-affinity", "create-skip-onboarding", "get-agent-status", "get-by-id", "get-dx", "get-export", "get-inventory", "get-inventory-export", "get-inventory-software-search-by-name", "get-inventory-software-search-by-upgrade-code", "get-my", "get-onboarding", "get-paged", "get-user-affinities", "get-user-affinities-export", "list", "update-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "computers.detected-computer-software",
				"description": "Manage detected computer software",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "computers.device-update-form-data",
				"description": "Manage device update form data",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "computers.ephemeral-agent",
				"description": "Manage ephemeral agent",
				"endpoints":   []string{"delete", "get"},
				"writable":    true,
			},
			{
				"name":        "computers.ephemeral-agent-circuit-breaker",
				"description": "Manage ephemeral agent circuit breaker",
				"endpoints":   []string{"create-reset", "get"},
				"writable":    true,
			},
			{
				"name":        "computers.events",
				"description": "Manage events",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "computers.exclude-from-maintenance",
				"description": "Manage exclude from maintenance",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "computers.exclude-from-user-affinity",
				"description": "Manage exclude from user affinity",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "computers.inventory-script-results",
				"description": "Manage inventory script results",
				"endpoints":   []string{"get-by-inventory-key"},
			},
			{
				"name":        "computers.launch-ephemeral-agent",
				"description": "Manage launch ephemeral agent",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "computers.notes",
				"description": "Manage notes",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "computers.parent-tenant-info",
				"description": "Manage parent tenant info",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "computers.provider-links",
				"description": "Manage provider links",
				"endpoints":   []string{"get-by-id-screen-share-url"},
			},
			{
				"name":        "computers.registry",
				"description": "Manage registry",
				"endpoints":   []string{"create-keys", "create-values"},
				"writable":    true,
			},
			{
				"name":        "computers.reinventory",
				"description": "Manage reinventory",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "computers.resolve-onboarding-overridable-target-assignments",
				"description": "Manage resolve onboarding overridable target assignments",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "computers.set-to-needs-onboarding",
				"description": "Manage set to needs onboarding",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "computers.status",
				"description": "Manage status",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "computers.update-additional-persons",
				"description": "Manage update additional persons",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "computers.update-primary-person",
				"description": "Manage update primary person",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "dynamic-provider-types",
				"description": "Manage dynamic provider types",
				"endpoints":   []string{"create-global", "create-global-by-id", "create-global-by-id-reload", "create-local", "create-local-by-id", "create-local-by-id-reload", "create-reload", "create-test-environment-by-terminal-id", "create-test-environment-by-terminal-id-bind-configuration-form", "create-test-environment-by-terminal-id-execute-method-by-method", "delete-global-by-id", "delete-local-by-id", "delete-test-environment-by-terminal-id", "get-global-by-id", "get-local-by-id", "list"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "effective-permissions",
				"description": "Manage effective permissions",
				"endpoints":   []string{"create-groups-by-group-id-evaluate-all-assignments", "create-groups-by-group-id-evaluate-resource", "create-groups-by-group-id-evaluate-tenant", "create-users-by-user-id-evaluate-all-assignments", "create-users-by-user-id-evaluate-resource", "create-users-by-user-id-evaluate-tenant"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "ephemeral-session",
				"description": "Manage ephemeral session",
				"endpoints":   []string{"get-by-agent-instance-id-by-provider-agent-id", "get-development-latest-ephemeral-binary", "get-development-latest-ephemeral-binary-v2"},
				"searchable":  true,
			},
			{
				"name":        "getting-started",
				"description": "Manage getting started",
				"endpoints":   []string{"create-checklist-complete", "create-checklist-reset", "get-checklist"},
				"writable":    true,
			},
			{
				"name":        "groups",
				"description": "Manage groups",
				"endpoints":   []string{"create", "delete-by-id", "get-by-id", "list", "update-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "groups.members",
				"description": "Manage members",
				"endpoints":   []string{"create", "create-bulk", "delete-by-user-id", "get"},
				"writable":    true,
			},
			{
				"name":        "groups.role-assignments",
				"description": "Manage role assignments",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "immy-agent-metadata",
				"description": "Manage immy agent metadata",
				"endpoints":   []string{"get-agent-hash"},
			},
			{
				"name":        "installer",
				"description": "Manage installer",
				"endpoints":   []string{"create-agent-rekey-request"},
				"writable":    true,
			},
			{
				"name":        "inventory-tasks",
				"description": "Manage inventory tasks",
				"endpoints":   []string{"create-local", "create-local-by-id", "create-local-by-id-scripts", "delete-local-by-id", "delete-local-by-task-id-scripts-by-inventory-key", "list"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "licenses",
				"description": "Manage licenses",
				"endpoints":   []string{"create", "create-upload", "delete-by-id", "get-by-id", "get-dx", "list", "update-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "licenses.request-download",
				"description": "Manage request download",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "maintenance-actions",
				"description": "Manage maintenance actions",
				"endpoints":   []string{"create-latest-action-for-computers", "create-latest-action-for-tenants", "get-computer-by-computer-id-needs-attention", "get-dx", "get-dx-for-computer-by-computer-id", "get-latest-for-computer-by-computer-id", "get-latest-for-tenant-by-tenant-id", "get-latest-non-compliant-actions-for-tenant-by-tenant-id", "get-maintenance-item", "get-version"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "maintenance-actions.logs",
				"description": "Manage logs",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "maintenance-emails",
				"description": "Manage maintenance emails",
				"endpoints":   []string{},
			},
			{
				"name":        "maintenance-emails.jobs",
				"description": "Manage jobs",
				"endpoints":   []string{"get-now", "get-postpone", "get-rebootnow"},
			},
			{
				"name":        "maintenance-sessions",
				"description": "Manage maintenance sessions",
				"endpoints":   []string{"create-cancel", "create-cancel-all", "create-rerun-v2", "get-by-session-id", "get-cancel-for-schedule-by-schedule-id", "get-dx", "get-status-counts"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "maintenance-sessions.actions",
				"description": "Manage actions",
				"endpoints":   []string{"create-by-id-rerun"},
				"writable":    true,
			},
			{
				"name":        "maintenance-sessions.cancel",
				"description": "Manage cancel",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "maintenance-sessions.last-log",
				"description": "Manage last log",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "maintenance-sessions.logs",
				"description": "Manage logs",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "maintenance-sessions.old-logs",
				"description": "Manage old logs",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "maintenance-sessions.phases",
				"description": "Manage phases",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "maintenance-sessions.rerun",
				"description": "Manage rerun",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "maintenance-sessions.resume",
				"description": "Manage resume",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "maintenance-tasks",
				"description": "Manage maintenance tasks",
				"endpoints":   []string{"create-duplicate", "create-global", "create-global-by-id", "create-global-by-id-param-block-from-parameters", "create-local", "create-local-by-id", "create-local-by-id-migrate-local-to-global", "create-local-by-id-param-block-from-parameters", "create-validate-param-block-parameters", "delete-global-by-id", "delete-local-by-id", "get-global", "get-global-by-id", "get-local", "get-local-by-id", "get-local-by-id-migrate-local-to-global-what-if", "get-reference-count", "get-search"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "maintenance-tasks.authorization",
				"description": "Manage authorization",
				"endpoints":   []string{"create", "get"},
				"writable":    true,
			},
			{
				"name":        "me",
				"description": "Manage me",
				"endpoints":   []string{"get-permissions"},
			},
			{
				"name":        "media",
				"description": "Manage media",
				"endpoints":   []string{"create-global-by-id", "create-global-upload", "create-local-by-id", "create-local-by-id-authorization", "create-local-upload", "create-request-file-download-url", "create-support-upload", "delete-global-by-id", "delete-local-by-id", "get-global", "get-global-by-id", "get-global-by-id-download-url", "get-local", "get-local-by-id", "get-local-by-id-authorization", "get-local-by-id-download-url", "get-search"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "metrics",
				"description": "Manage metrics",
				"endpoints":   []string{"create-circuit-breakers-isolate", "create-circuit-breakers-reset", "get-circuit-breakers", "get-provider-links", "get-provider-links-by-provider-link-id-rate-limit-statistics"},
				"syncable":    true,
				"writable":    true,
			},
			{
				"name":        "notifications",
				"description": "Manage notifications",
				"endpoints":   []string{"create-acknowledge", "get-dx", "get-unacknowledged", "list"},
				"syncable":    true,
				"writable":    true,
			},
			{
				"name":        "notifications.silence",
				"description": "Manage silence",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "notifications.unsilence",
				"description": "Manage unsilence",
				"endpoints":   []string{"delete"},
				"writable":    true,
			},
			{
				"name":        "oauth",
				"description": "Manage oauth",
				"endpoints":   []string{"create-access-tokens-by-id-refresh", "create-begin-auth-code-flow", "create-fail-auth-code-flow", "create-finish-auth-code-flow", "delete-access-tokens-by-id", "get-access-tokens", "get-access-tokens-by-id-by-access-token-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "persons",
				"description": "Manage persons",
				"endpoints":   []string{"create", "create-add-tags", "create-remove-tags", "delete-by-id", "get-by-id", "get-dx", "get-requesting-access", "list", "update-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "persons.deny-access",
				"description": "Manage deny access",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "persons.detected-software",
				"description": "Manage detected software",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "persons.grant-access",
				"description": "Manage grant access",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "persons.self-service",
				"description": "Manage self service",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "plugins",
				"description": "Manage plugins",
				"endpoints":   []string{"create-api-v1-by-provider-link-id-by-catch-all", "get-api-v1-by-provider-link-id-by-catch-all", "get-api-v1-by-provider-link-id-by-catch-all-v2"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "preferences",
				"description": "Manage preferences",
				"endpoints":   []string{"get-tenants-by-tenant-id", "list", "update-application", "update-my", "update-tenants-by-tenant-id"},
				"syncable":    true,
				"writable":    true,
			},
			{
				"name":        "provider-agents",
				"description": "Manage provider agents",
				"endpoints":   []string{"create-bulk-delete-pending", "create-identify", "create-resolve-failure-by-failure-id", "create-resolve-failures", "get-pending", "get-pending-counts"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "provider-agents.identification-logs",
				"description": "Manage identification logs",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "provider-agents.pending-conflicts",
				"description": "Manage pending conflicts",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "provider-agents.resolve-failures",
				"description": "Manage resolve failures",
				"endpoints":   []string{"create-by-agent-id"},
				"writable":    true,
			},
			{
				"name":        "provider-links",
				"description": "Manage provider links",
				"endpoints":   []string{"create", "create-create-with-external-provider-reference", "create-verify-with-external-provider-reference", "delete-by-id", "get-by-id", "list", "update-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "provider-links.agents",
				"description": "Manage agents",
				"endpoints":   []string{"create-bash-install-script", "create-bash-install-script-with-onboarding", "create-by-computer-id-external-url", "create-by-id-delete-offline-from-computer", "create-by-id-refresh-device-online-status", "create-executable-uri", "create-executable-uri-with-onboarding", "create-install-on-computer-by-computer-id", "create-powershell-install-script", "create-powershell-install-script-with-onboarding", "create-provisioning-package-uri", "create-provisioning-package-uri-with-onboarding", "create-sync"},
				"writable":    true,
			},
			{
				"name":        "provider-links.asset-field-mappings",
				"description": "Manage asset field mappings",
				"endpoints":   []string{"create", "delete-by-mapping-id", "get", "update-by-mapping-id"},
				"writable":    true,
			},
			{
				"name":        "provider-links.asset-fields",
				"description": "Manage asset fields",
				"endpoints":   []string{"get", "get-by-external-field-id-samples"},
			},
			{
				"name":        "provider-links.asset-match-fields",
				"description": "Manage asset match fields",
				"endpoints":   []string{"create", "delete-by-match-field-id", "get", "get-recommended", "update-by-match-field-id"},
				"writable":    true,
			},
			{
				"name":        "provider-links.assets",
				"description": "Manage assets",
				"endpoints":   []string{"create-trigger", "get-by-external-id-url", "get-dx", "get-job-state", "get-schedule"},
				"writable":    true,
			},
			{
				"name":        "provider-links.audits",
				"description": "Manage audits",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "provider-links.clients",
				"description": "Manage clients",
				"endpoints":   []string{"create-auto-link-to-tenants", "create-link-exact-match", "create-link-to-new-tenant", "create-link-to-tenant", "create-sync", "create-sync-agents", "create-unlink-from-tenants", "get", "get-statuses", "get-types"},
				"writable":    true,
			},
			{
				"name":        "provider-links.cross-references",
				"description": "Manage cross references",
				"endpoints":   []string{"create-by-external-link-id-disable-client-linking", "create-by-external-link-id-enable-client-linking", "create-by-external-link-id-sync-clients", "create-create", "delete-by-external-link-id-delete"},
				"writable":    true,
			},
			{
				"name":        "provider-links.immy-field-samples",
				"description": "Manage immy field samples",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "provider-links.reload",
				"description": "Manage reload",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "provider-links.tickets",
				"description": "Manage tickets",
				"endpoints":   []string{"get-by-id"},
			},
			{
				"name":        "provider-types",
				"description": "Manage provider types",
				"endpoints":   []string{"get-client-group-types-by-client-group-type-id-client-groups", "get-device-group-types-by-device-group-type-id-device-groups", "get-form-dropdown-options-by-key", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "provider-types.bind-parameters",
				"description": "Manage bind parameters",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "rmm-links",
				"description": "Manage rmm links",
				"endpoints":   []string{"create", "get-by-id", "list", "update-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "roles",
				"description": "Manage roles",
				"endpoints":   []string{"create", "delete-by-id", "get-by-id", "get-permissions", "list", "update-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "roles.assignments",
				"description": "Manage assignments",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "roles.clone",
				"description": "Manage clone",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "run-immy-service",
				"description": "Manage run immy service",
				"endpoints":   []string{"create"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "run-immy-service-new",
				"description": "Manage run immy service new",
				"endpoints":   []string{"create"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "schedules",
				"description": "Manage schedules",
				"endpoints":   []string{"create", "create-bulk-cancel", "create-bulk-delete", "create-bulk-run-now", "delete-by-id", "get-by-id", "get-running-ids", "list", "update-bulk-update-status", "update-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "schedules.cancel",
				"description": "Manage cancel",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "schedules.duplicate",
				"description": "Manage duplicate",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "schedules.run-now",
				"description": "Manage run now",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "scripts",
				"description": "Manage scripts",
				"endpoints":   []string{"create-debug-cancel-by-cancellation-id", "create-default-variables", "create-does-have-param-block", "create-duplicate", "create-functions-syntax", "create-global", "create-global-by-id", "create-language-service-start", "create-local", "create-local-by-id", "create-local-by-id-authorization", "create-local-by-id-migrate-local-to-global", "create-run", "create-run-adhoc-metascript", "create-set-preflight-enablement", "create-syntax-check", "create-validate-param-block-parameters", "delete-global-by-id", "delete-local-by-id", "get-disabled-preflight", "get-dx", "get-functions", "get-global", "get-global-by-id", "get-global-by-id-audit", "get-global-by-id-references", "get-global-names", "get-language-service-by-terminal-id-language", "get-local", "get-local-by-id", "get-local-by-id-audit", "get-local-by-id-authorization", "get-local-by-id-migrate-local-to-global-what-if", "get-local-by-id-references", "get-local-names", "get-references-count", "get-search"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "smtp-configs",
				"description": "Manage smtp configs",
				"endpoints":   []string{"create", "create-by-tenant-id", "create-send-test-email", "delete-by-tenant-id", "get-by-tenant-id", "list"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "software",
				"description": "Manage software",
				"endpoints":   []string{"create-global", "create-global-analyze", "create-global-by-identifier-versions", "create-global-fast-create", "create-global-upload", "create-local", "create-local-analyze", "create-local-by-identifier-authorization", "create-local-by-identifier-migrate-local-to-global", "create-local-by-identifier-versions", "create-local-fast-create", "create-local-upload", "delete-global-by-identifier", "delete-global-by-identifier-versions-by-semantic-version", "delete-local-by-identifier", "delete-local-by-identifier-versions-by-semantic-version", "get-global", "get-global-by-identifier", "get-global-by-identifier-latest", "get-global-by-identifier-versions", "get-global-by-identifier-versions-by-semantic-version", "get-global-by-identifier-versions-by-semantic-version-request-download", "get-local", "get-local-by-identifier", "get-local-by-identifier-authorization", "get-local-by-identifier-latest", "get-local-by-identifier-migrate-local-to-global-what-if", "get-local-by-identifier-versions", "get-local-by-identifier-versions-by-semantic-version", "get-local-by-identifier-versions-by-semantic-version-request-download", "update-global-by-identifier", "update-global-by-identifier-versions-by-semantic-version", "update-local-by-identifier", "update-local-by-identifier-versions-by-semantic-version"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "syncs",
				"description": "Manage syncs",
				"endpoints":   []string{"create-azure-user", "create-expire-pending-sessions", "create-trigger-user-affinity"},
				"writable":    true,
			},
			{
				"name":        "system",
				"description": "Manage system",
				"endpoints":   []string{"create-disable-immy-support-access", "create-enable-immy-support-access", "create-is-immy-support-access-granted", "create-pull-update", "create-request-form-support", "create-request-session-support", "create-restart-backend", "create-update-release-channel", "get-immy-support-access-grant-details", "get-releases", "get-timezones"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "tags",
				"description": "Manage tags",
				"endpoints":   []string{"create", "create-by-id", "delete-by-id", "get-by-id", "list"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "tags.authorization",
				"description": "Manage authorization",
				"endpoints":   []string{"create", "get"},
				"writable":    true,
			},
			{
				"name":        "target-assignments",
				"description": "Manage target assignments",
				"endpoints":   []string{"create", "create-change-request-by-change-request-id-v2", "create-change-request-v2", "create-duplicate", "create-duplicates", "create-global-by-id-notes", "create-global-by-id-override", "create-global-create", "create-migrate-deployments-to-provider-links", "create-migrate-to-superseding-assignment", "create-migrate-to-superseding-assignment-what-if", "create-optional-approvals-by-id", "create-persons-target-preview", "create-recommended-approvals-update", "create-target-preview", "create-tenant-target-preview", "create-update-maintenance-item-order", "create-visibility", "delete-by-id", "delete-global-by-id", "get-by-id", "get-change-request-by-change-request-id", "get-change-request-by-change-request-id-diff", "get-change-requests", "get-global", "get-global-by-id", "get-global-by-id-type", "get-maintenance-item-orders", "get-optional-approvals-computer-by-computer-id", "get-recommended-approvals", "list", "update-batch-update", "update-by-id", "update-global-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "target-assignments.change-request",
				"description": "Manage change request",
				"endpoints":   []string{"create", "create-by-id"},
				"writable":    true,
			},
			{
				"name":        "target-assignments.change-requests",
				"description": "Manage change requests",
				"endpoints":   []string{"get-by-deployment-id"},
			},
			{
				"name":        "target-assignments.notes",
				"description": "Manage notes",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "target-assignments.override",
				"description": "Manage override",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "target-assignments.type",
				"description": "Manage type",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "tenants",
				"description": "Manage tenants",
				"endpoints":   []string{"create", "create-add-tags", "create-bulk-create", "create-bulk-delete", "create-bulk-merge", "create-remove-parent", "create-remove-tags", "create-resolve-assignments-for-maintenance-item", "create-set-parent", "create-update-azure-link", "get-by-id", "get-computer-counts", "get-excluded-from-cross-deployments", "get-software-from-inventory-by-id", "get-software-from-inventory-dx", "get-software-from-inventory-export", "list", "update-activate-by-id", "update-by-id", "update-deactivate-by-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "tenants.azure-groups",
				"description": "Manage azure groups",
				"endpoints":   []string{"get", "get-by-group-id"},
			},
			{
				"name":        "tenants.computers",
				"description": "Manage computers",
				"endpoints":   []string{"get-excluded-from-maintenance"},
			},
			{
				"name":        "user-role-assignments",
				"description": "Manage user role assignments",
				"endpoints":   []string{"create-category-resource-create", "create-msp-create", "create-owner-create", "create-specific-resource-create", "create-specific-tenant-create", "create-tag-resource-create", "create-tenant-tag-create", "create-user-tenant-create", "delete-delete", "get-users-by-user-id", "get-users-by-user-id-count", "list"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "user_session",
				"description": "Manage user session",
				"endpoints":   []string{"get-login", "get-logout", "get-me", "get-refresh"},
				"searchable":  true,
			},
			{
				"name":        "users",
				"description": "Manage users",
				"endpoints":   []string{"create-bulk-create", "create-by-id", "create-invalidate-cache", "create-stop-impersonating", "create-submit-feedback", "create-update-expiration", "delete-bulk-delete", "delete-by-id", "get-by-id", "get-claims", "list"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "users.groups",
				"description": "Manage groups",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "users.impersonate",
				"description": "Manage impersonate",
				"endpoints":   []string{"create"},
				"writable":    true,
			},
			{
				"name":        "webhooks",
				"description": "Manage webhooks",
				"endpoints":   []string{"create-by-id", "get-by-id"},
				"searchable":  true,
				"writable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass Page parameter for subsequent pages.",
			"Control page size with the PageSize parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Maintenance failure clustering", "command": "session-triage", "description": "Group last night's failed maintenance actions by root cause instead of reading the same error on forty machines.", "rationale": "Requires a local join from maintenance sessions to actions to computers to tenants; no endpoint returns failures grouped by cause across sessions.", "via": "mcp-command-mirror"},
			{"name": "Deployment resolution explainer", "command": "assignment-explain", "description": "Show every target assignment that resolves onto one computer, which scope matched, and which rules are shadowed.", "rationale": "Target assignments are resolution rules rather than direct links, so the winning rule can only be computed from local assignments plus group, tag, and tenant membership.", "via": "mcp-command-mirror"},
			{"name": "Cross-tenant version spread", "command": "version-spread", "description": "Semver-ordered distribution of one software title across every tenant, flagging everything below a floor.", "rationale": "Every existing tool is per-tenant and compares versions as strings, so 9.0 sorts above 140.0; this needs synced inventory and a real comparator.", "via": "mcp-command-mirror"},
			{"name": "Sync-to-sync fleet diff", "command": "fleet-diff", "description": "What actually changed between two syncs: computers added or removed, software versions moved, assignments modified.", "rationale": "The API has no updated-since cursor, so change detection is impossible from any call and exists only because the local store keeps snapshots.", "via": "mcp-command-mirror"},
			{"name": "Script blast radius", "command": "script-blast-radius", "description": "Every maintenance task, software package, and computer that a script reaches before you edit it.", "rationale": "Requires a multi-hop local walk from scripts to tasks and software to target assignments to the computers those assignments resolve onto.", "via": "mcp-command-mirror"},
			{"name": "Stalled onboarding queue", "command": "onboarding-stalled", "description": "Computers stuck waiting to onboard, bucketed by age and annotated with whether onboarding was ever attempted.", "rationale": "Joins onboarding queue state to onboarding-type maintenance sessions; the bare queue endpoint is a flat list with no age and no outcome.", "via": "mcp-command-mirror"},
			{"name": "PSA and RMM link reconciliation", "command": "psa-reconcile", "description": "Diff the ImmyBot roster against a linked PSA or RMM asset roster to find unlinked computers and orphaned assets.", "rationale": "Provider links are the largest endpoint family in the API and both rosters are exposed, but nothing joins them.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Maintenance failure clustering", "insight": "Requires a local join from maintenance sessions to actions to computers to tenants; no endpoint returns failures grouped by cause across sessions."},
			{"topic": "Deployment resolution explainer", "insight": "Target assignments are resolution rules rather than direct links, so the winning rule can only be computed from local assignments plus group, tag, and tenant membership."},
			{"topic": "Cross-tenant version spread", "insight": "Every existing tool is per-tenant and compares versions as strings, so 9.0 sorts above 140.0; this needs synced inventory and a real comparator."},
			{"topic": "Sync-to-sync fleet diff", "insight": "The API has no updated-since cursor, so change detection is impossible from any call and exists only because the local store keeps snapshots."},
			{"topic": "Script blast radius", "insight": "Requires a multi-hop local walk from scripts to tasks and software to target assignments to the computers those assignments resolve onto."},
			{"topic": "Stalled onboarding queue", "insight": "Joins onboarding queue state to onboarding-type maintenance sessions; the bare queue endpoint is a flat list with no age and no outcome."},
			{"topic": "PSA and RMM link reconciliation", "insight": "Provider links are the largest endpoint family in the API and both rosters are exposed, but nothing joins them."},
			{"topic": "Finding stale work", "insight": "Use the stale command or sql query to find items not updated recently. More reliable than scanning list results manually."},
			{"topic": "Load analysis", "insight": "When analyzing team workload, filter by assignee and status. Raw counts without status filtering are misleading."},
			{"topic": "Bulk operations", "insight": "For bulk status changes, prefer update endpoints over delete+create. Most PM APIs track history on updates."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
