// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"os"

	"avanan-pp-cli/internal/cliutil"
	"avanan-pp-cli/internal/config"
	"github.com/spf13/cobra"
)

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "auth",
		Short:       "Manage authentication for Avanan",
		Annotations: map[string]string{"pp:parent-group": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthSetupCmd(flags))
	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))

	return cmd
}

// newAuthSetupCmd prints concrete steps for getting a credential. Side-effect
// rule: print by default, --launch opt-in to open the URL, short-circuit when
// the verifier is running this in a sandboxed subprocess.
func newAuthSetupCmd(_ *rootFlags) *cobra.Command {
	var launch bool
	cmd := &cobra.Command{
		Use:     "setup",
		Short:   "Print the steps for obtaining a credential",
		Example: "  avanan-cli auth setup",
		RunE: func(cmd *cobra.Command, args []string) error {
			w := cmd.OutOrStdout()
			// `doctor` and the HTTP 401/403 hints send operators here, so this
			// has to answer with the real steps. Avanan publishes no stable
			// deep link to the key page, hence no URL to launch -- but the
			// steps below are exact, and are the same credentials `auth login`
			// reads.
			fmt.Fprintln(w, "Create an Avanan API key, then authenticate:")
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "  1. In the Avanan / Infinity Portal web console, open")
			fmt.Fprintln(w, "     Settings -> API Keys and create a key. Note the region it is")
			fmt.Fprintln(w, "     issued for: keys are region-scoped and a key issued for one")
			fmt.Fprintln(w, "     region cannot read another region's data.")
			fmt.Fprintln(w, "  2. Export the application ID and client secret:")
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "     export AVANAN_APP_ID=\"your-application-id\"")
			fmt.Fprintln(w, "     export AVANAN_CLIENT_SECRET=\"your-client-secret\"")
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "  3. Exchange them for a session token, naming the same region:")
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "     avanan-cli auth login --region <us|eu|ca|ap|uk|uae|in|infinity|infinity-us> --save")
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "     For a gateway with no region code, set AVANAN_BASE_URL instead.")
			fmt.Fprintln(w, "  4. Confirm it worked:")
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "     avanan-cli doctor")
			if !launch {
				return nil
			}
			fmt.Fprintln(cmd.ErrOrStderr(), "Avanan publishes no stable setup URL to open; follow the steps above.")
			return nil
		},
	}
	cmd.Flags().BoolVar(&launch, "launch", false, "Deprecated: Avanan publishes no stable setup URL, so there is nothing to open")
	return cmd
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "status",
		Short:   "Show authentication status",
		Example: "  avanan-cli auth status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			w := cmd.OutOrStdout()
			header := cfg.AuthHeader()
			authed := header != ""
			// JSON envelope: {authenticated, verified, source, config}. When not
			// authenticated, write the envelope first then return authErr
			// so exit code carries the auth-failure signal.
			if flags.asJSON {
				out := map[string]any{
					"authenticated": authed,
					"verified":      false,
					"source":        cfg.AuthSource,
					"config":        cfg.Path,
				}
				if printErr := printJSONFiltered(w, out, flags); printErr != nil {
					return printErr
				}
				if !authed {
					return authErr(fmt.Errorf("no credentials configured"))
				}
				return nil
			}
			if !authed {
				fmt.Fprintln(w, red("Not authenticated"))
				fmt.Fprintln(w, "")
				fmt.Fprintln(w, "Set your token:")
				return authErr(fmt.Errorf("no credentials configured"))
			}

			fmt.Fprintln(w, green("Credentials present (not verified)"))
			fmt.Fprintf(w, "  Source: %s\n", cfg.AuthSource)
			fmt.Fprintf(w, "  Config: %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthSetTokenCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "set-token <token>",
		Short:   "Save an API token to the credentials file",
		Example: "  avanan-cli auth set-token YOUR_TOKEN_HERE",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			// Clear any legacy auth_header so AuthHeader() falls through to
			// the newly-saved credential. Without this, a pre-existing
			// auth_header value (common after regenerate) shadows the saved
			// token and set-token silently has no effect. Silent clear (no
			// log line): a masked-tail variant could leak token bytes through
			// scripted dogfood that captures stderr.
			cfg.AuthHeaderVal = ""
			// api_key auth: AuthHeader() reads the env-var-derived field, not
			// AccessToken. Writing the token to AccessToken via SaveTokens
			// would persist the bytes but leave doctor reporting "not
			// configured" — the slot the header builder consults stays empty.
			if err := cfg.SaveCredential(args[0]); err != nil {
				return configErr(fmt.Errorf("saving token: %w", err))
			}

			savePath := credentialSavePath(cfg)
			// JSON envelope: {saved, config_path, credentials_path}.
			if flags.asJSON {
				out := map[string]any{
					"saved":       true,
					"config_path": cfg.Path,
				}
				if !cfg.AgentcookieManagedByExternalStore() {
					out["credentials_path"] = savePath
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Token saved to %s\n", savePath)
			return nil
		},
	}
}

func credentialSavePath(cfg *config.Config) string {
	if cfg != nil && cfg.AgentcookieManagedByExternalStore() {
		return cfg.Path
	}
	if path, err := cliutil.CredentialsFilePath(); err == nil {
		return path
	}
	if cfg != nil {
		return cfg.Path
	}
	return ""
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "logout",
		Short:   "Clear stored credentials",
		Example: "  avanan-cli auth logout",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.ClearTokens(); err != nil {
				return configErr(fmt.Errorf("clearing tokens: %w", err))
			}

			// Identify which (if any) auth env var is still exported so the
			// JSON envelope and the human prose can both surface it.
			envStillSet := ""
			if envStillSet == "" && os.Getenv("AVANAN_APP_ID") != "" {
				envStillSet = "AVANAN_APP_ID"
			}
			if envStillSet == "" && os.Getenv("AVANAN_CLIENT_SECRET") != "" {
				envStillSet = "AVANAN_CLIENT_SECRET"
			}
			if envStillSet == "" && os.Getenv("AVANAN_TOKEN") != "" {
				envStillSet = "AVANAN_TOKEN"
			}

			// JSON envelope: {cleared: true, note?: "<env_var> env var is still set"}.
			if flags.asJSON {
				out := map[string]any{"cleared": true}
				if envStillSet != "" {
					out["note"] = envStillSet + " env var is still set"
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if envStillSet != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "Config cleared. Note: %s env var is still set.\n", envStillSet)
				return nil
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Logged out. Credentials cleared.")
			return nil
		},
	}
}
