// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"avanan-pp-cli/internal/cliutil"
	"github.com/spf13/cobra"
)

func newAvananSearchQuerySaasEntityCmd(flags *rootFlags) *cobra.Command {
	var flagScopes string
	var flagXAvReqId string
	var bodyRequestDataEntityExtendedFilter string
	var bodyRequestDataEntityFilterEndDate string
	var bodyRequestDataEntityFilterSaas string
	var bodyRequestDataEntityFilterSaasEntity string
	var bodyRequestDataEntityFilterStartDate string
	var bodyRequestDataScopes string
	var bodyRequestDataScrollId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:     "query-saas-entity",
		Aliases: []string{"create"},
		Short:   "Query Saas Entity.",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  avanan-cli avanan-search query-saas-entity --scopes example-value --x-av-req-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "avanan-search.query-saas-entity", "pp:method": "POST", "pp:path": "/v1.0/search/query", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("request-data-entity-filter-saas") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-entity-filter-saas")
				}
				if !cmd.Flags().Changed("request-data-entity-filter-start-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-entity-filter-start-date")
				}
			}
			path := "/v1.0/search/query"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			headerOverrides := map[string]string{}

			if cmd.Flags().Changed("scopes") || flagScopes != "" {
				headerOverrides["scopes"] = formatCLIParamValue(flagScopes)
			}

			if cmd.Flags().Changed("x-av-req-id") || flagXAvReqId != "" {
				headerOverrides["x-av-req-id"] = formatCLIParamValue(flagXAvReqId)
			}

			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				{
					nestedRequestData := map[string]any{}
					if cmd.Flags().Changed("request-data-entity-extended-filter") || bodyRequestDataEntityExtendedFilter != "" {
						var parsedRequestDataEntityExtendedFilter any
						if err := json.Unmarshal([]byte(bodyRequestDataEntityExtendedFilter), &parsedRequestDataEntityExtendedFilter); err != nil {
							return fmt.Errorf("parsing --request-data-entity-extended-filter JSON: %w", err)
						}
						asArray, ok := parsedRequestDataEntityExtendedFilter.([]any)
						if !ok {
							return fmt.Errorf("--request-data-entity-extended-filter must be a JSON array, got JSON %T", parsedRequestDataEntityExtendedFilter)
						}
						nestedRequestData["entityExtendedFilter"] = asArray
					}
					{
						nestedRequestDataEntityFilter := map[string]any{}
						if cmd.Flags().Changed("request-data-entity-filter-end-date") || bodyRequestDataEntityFilterEndDate != "" {
							nestedRequestDataEntityFilter["endDate"] = bodyRequestDataEntityFilterEndDate
						}
						if cmd.Flags().Changed("request-data-entity-filter-saas") || bodyRequestDataEntityFilterSaas != "" {
							nestedRequestDataEntityFilter["saas"] = bodyRequestDataEntityFilterSaas
						}
						if cmd.Flags().Changed("request-data-entity-filter-saas-entity") || bodyRequestDataEntityFilterSaasEntity != "" {
							nestedRequestDataEntityFilter["saasEntity"] = bodyRequestDataEntityFilterSaasEntity
						}
						if cmd.Flags().Changed("request-data-entity-filter-start-date") || bodyRequestDataEntityFilterStartDate != "" {
							nestedRequestDataEntityFilter["startDate"] = bodyRequestDataEntityFilterStartDate
						}
						if len(nestedRequestDataEntityFilter) > 0 {
							nestedRequestData["entityFilter"] = nestedRequestDataEntityFilter
						}
					}
					if cmd.Flags().Changed("request-data-scopes") {
						parsedRequestDataScopes, parseErr := cliutil.ParseStringList(bodyRequestDataScopes)
						if parseErr != nil {
							return fmt.Errorf("parsing --request-data-scopes list: %w", parseErr)
						}
						nestedRequestData["scopes"] = parsedRequestDataScopes
					}
					if cmd.Flags().Changed("request-data-scroll-id") || bodyRequestDataScrollId != "" {
						nestedRequestData["scrollId"] = bodyRequestDataScrollId
					}
					if len(nestedRequestData) > 0 {
						bodyMap["requestData"] = nestedRequestData
					}
				}
			}
			data, statusCode, err := c.PostQueryWithParamsAndHeaders(cmd.Context(), path, params, body, headerOverrides)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "avanan-search", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "avanan-search", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "avanan-search", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "avanan-search", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "avanan-search",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "avanan-search", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "avanan-search", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&flagScopes, "scopes", "", "Scopes")
	cmd.Flags().StringVar(&flagXAvReqId, "x-av-req-id", "", "X av req id")
	cmd.Flags().StringVar(&bodyRequestDataEntityExtendedFilter, "request-data-entity-extended-filter", "", "Entity extended filter")
	cmd.Flags().StringVar(&bodyRequestDataEntityFilterEndDate, "request-data-entity-filter-end-date", "", "End date")
	cmd.Flags().StringVar(&bodyRequestDataEntityFilterSaas, "request-data-entity-filter-saas", "", "Saas")
	cmd.Flags().StringVar(&bodyRequestDataEntityFilterSaasEntity, "request-data-entity-filter-saas-entity", "", "Saas entity")
	cmd.Flags().StringVar(&bodyRequestDataEntityFilterStartDate, "request-data-entity-filter-start-date", "", "Start date")
	cmd.Flags().StringVar(&bodyRequestDataScopes, "request-data-scopes", "", "Scopes")
	cmd.Flags().StringVar(&bodyRequestDataScrollId, "request-data-scroll-id", "", "Scroll id")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
