// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEventCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "event",
		Short:       "Get and query event",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEventGetCmd(flags))
	cmd.AddCommand(newEventQueryCmd(flags))
	return cmd
}
