// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newExceptionsUpdateCmd(flags *rootFlags) *cobra.Command {
	var flagScope string
	var flagScopes string
	var flagXAvReqId string
	var bodyRequestDataActionNeeded string
	var bodyRequestDataAttachmentMd5 string
	var bodyRequestDataComment string
	var bodyRequestDataEntityId string
	var bodyRequestDataIgnoringSpfCheck bool
	var bodyRequestDataLinkDomainMatching string
	var bodyRequestDataLinkDomains string
	var bodyRequestDataMatchOnlyFuture bool
	var bodyRequestDataQuarantineAll bool
	var bodyRequestDataRecipient string
	var bodyRequestDataRecipientMatching string
	var bodyRequestDataSenderClientIp string
	var bodyRequestDataSenderDomain string
	var bodyRequestDataSenderDomainMatching string
	var bodyRequestDataSenderEmail string
	var bodyRequestDataSenderEmailMatching string
	var bodyRequestDataSenderIp string
	var bodyRequestDataSenderName string
	var bodyRequestDataSenderNameMatching string
	var bodyRequestDataSubject string
	var bodyRequestDataSubjectMatching string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "update <exc_id>",
		Short: "Update Ap Exception Blacklist.",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  avanan-cli exceptions update 550e8400-e29b-41d4-a716-446655440000 --scopes example-value --x-av-req-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "exceptions.update", "pp:method": "PUT", "pp:path": "/v1.0/exceptions/blacklist/{exc_id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <exc_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <exc_id>"))
			}
			if !stdinBody {
			}
			path := "/v1.0/exceptions/blacklist/{exc_id}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("exc_id is required\nUsage: %s <%s>", cmd.CommandPath(), "exc_id"))
			}
			path = replacePathParam(path, "exc_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			headerOverrides := map[string]string{}

			if cmd.Flags().Changed("scopes") || flagScopes != "" {
				headerOverrides["scopes"] = formatCLIParamValue(flagScopes)
			}

			if cmd.Flags().Changed("x-av-req-id") || flagXAvReqId != "" {
				headerOverrides["x-av-req-id"] = formatCLIParamValue(flagXAvReqId)
			}

			params := map[string]string{}
			if cmd.Flags().Changed("scope") || flagScope != "" {
				params["scope"] = formatCLIParamValue(flagScope)
			}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				{
					nestedRequestData := map[string]any{}
					if cmd.Flags().Changed("request-data-action-needed") || bodyRequestDataActionNeeded != "" {
						nestedRequestData["actionNeeded"] = bodyRequestDataActionNeeded
					}
					if cmd.Flags().Changed("request-data-attachment-md5") || bodyRequestDataAttachmentMd5 != "" {
						nestedRequestData["attachmentMd5"] = bodyRequestDataAttachmentMd5
					}
					if cmd.Flags().Changed("request-data-comment") || bodyRequestDataComment != "" {
						nestedRequestData["comment"] = bodyRequestDataComment
					}
					if cmd.Flags().Changed("request-data-entity-id") || bodyRequestDataEntityId != "" {
						nestedRequestData["entityId"] = bodyRequestDataEntityId
					}
					if cmd.Flags().Changed("request-data-ignoring-spf-check") {
						nestedRequestData["ignoringSpfCheck"] = bodyRequestDataIgnoringSpfCheck
					}
					if cmd.Flags().Changed("request-data-link-domain-matching") || bodyRequestDataLinkDomainMatching != "" {
						nestedRequestData["linkDomainMatching"] = bodyRequestDataLinkDomainMatching
					}
					if cmd.Flags().Changed("request-data-link-domains") || bodyRequestDataLinkDomains != "" {
						if looksLikeJSONComposite(bodyRequestDataLinkDomains) {
							var parsedRequestDataLinkDomains any
							if err := json.Unmarshal([]byte(bodyRequestDataLinkDomains), &parsedRequestDataLinkDomains); err != nil {
								return fmt.Errorf("parsing --request-data-link-domains JSON: %w", err)
							}
							nestedRequestData["linkDomains"] = parsedRequestDataLinkDomains
						} else {
							nestedRequestData["linkDomains"] = bodyRequestDataLinkDomains
						}
					}
					if cmd.Flags().Changed("request-data-match-only-future") {
						nestedRequestData["matchOnlyFuture"] = bodyRequestDataMatchOnlyFuture
					}
					if cmd.Flags().Changed("request-data-quarantine-all") {
						nestedRequestData["quarantineAll"] = bodyRequestDataQuarantineAll
					}
					if cmd.Flags().Changed("request-data-recipient") || bodyRequestDataRecipient != "" {
						nestedRequestData["recipient"] = bodyRequestDataRecipient
					}
					if cmd.Flags().Changed("request-data-recipient-matching") || bodyRequestDataRecipientMatching != "" {
						nestedRequestData["recipientMatching"] = bodyRequestDataRecipientMatching
					}
					if cmd.Flags().Changed("request-data-sender-client-ip") || bodyRequestDataSenderClientIp != "" {
						nestedRequestData["senderClientIp"] = bodyRequestDataSenderClientIp
					}
					if cmd.Flags().Changed("request-data-sender-domain") || bodyRequestDataSenderDomain != "" {
						nestedRequestData["senderDomain"] = bodyRequestDataSenderDomain
					}
					if cmd.Flags().Changed("request-data-sender-domain-matching") || bodyRequestDataSenderDomainMatching != "" {
						nestedRequestData["senderDomainMatching"] = bodyRequestDataSenderDomainMatching
					}
					if cmd.Flags().Changed("request-data-sender-email") || bodyRequestDataSenderEmail != "" {
						nestedRequestData["senderEmail"] = bodyRequestDataSenderEmail
					}
					if cmd.Flags().Changed("request-data-sender-email-matching") || bodyRequestDataSenderEmailMatching != "" {
						nestedRequestData["senderEmailMatching"] = bodyRequestDataSenderEmailMatching
					}
					if cmd.Flags().Changed("request-data-sender-ip") || bodyRequestDataSenderIp != "" {
						nestedRequestData["senderIp"] = bodyRequestDataSenderIp
					}
					if cmd.Flags().Changed("request-data-sender-name") || bodyRequestDataSenderName != "" {
						nestedRequestData["senderName"] = bodyRequestDataSenderName
					}
					if cmd.Flags().Changed("request-data-sender-name-matching") || bodyRequestDataSenderNameMatching != "" {
						nestedRequestData["senderNameMatching"] = bodyRequestDataSenderNameMatching
					}
					if cmd.Flags().Changed("request-data-subject") || bodyRequestDataSubject != "" {
						nestedRequestData["subject"] = bodyRequestDataSubject
					}
					if cmd.Flags().Changed("request-data-subject-matching") || bodyRequestDataSubjectMatching != "" {
						nestedRequestData["subjectMatching"] = bodyRequestDataSubjectMatching
					}
					if len(nestedRequestData) > 0 {
						bodyMap["requestData"] = nestedRequestData
					}
				}
			}
			data, statusCode, err := c.PutWithParamsAndHeaders(cmd.Context(), path, params, body, headerOverrides)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "exceptions", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "exceptions", data, "responseData")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "exceptions", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "exceptions", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "exceptions", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "exceptions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "exceptions", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "exceptions", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&flagScope, "scope", "", "Scope")
	cmd.Flags().StringVar(&flagScopes, "scopes", "", "Scopes")
	cmd.Flags().StringVar(&flagXAvReqId, "x-av-req-id", "", "X av req id")
	cmd.Flags().StringVar(&bodyRequestDataActionNeeded, "request-data-action-needed", "", "Action needed")
	cmd.Flags().StringVar(&bodyRequestDataAttachmentMd5, "request-data-attachment-md5", "", "Attachment md5")
	cmd.Flags().StringVar(&bodyRequestDataComment, "request-data-comment", "", "Comment")
	cmd.Flags().StringVar(&bodyRequestDataEntityId, "request-data-entity-id", "", "Entity id")
	cmd.Flags().BoolVar(&bodyRequestDataIgnoringSpfCheck, "request-data-ignoring-spf-check", false, "Ignoring spf check")
	cmd.Flags().StringVar(&bodyRequestDataLinkDomainMatching, "request-data-link-domain-matching", "", "An enumeration.")
	cmd.Flags().StringVar(&bodyRequestDataLinkDomains, "request-data-link-domains", "", "Link domains")
	cmd.Flags().BoolVar(&bodyRequestDataMatchOnlyFuture, "request-data-match-only-future", false, "Match only future")
	cmd.Flags().BoolVar(&bodyRequestDataQuarantineAll, "request-data-quarantine-all", false, "Quarantine all")
	cmd.Flags().StringVar(&bodyRequestDataRecipient, "request-data-recipient", "", "Recipient")
	cmd.Flags().StringVar(&bodyRequestDataRecipientMatching, "request-data-recipient-matching", "", "An enumeration.")
	cmd.Flags().StringVar(&bodyRequestDataSenderClientIp, "request-data-sender-client-ip", "", "Sender client ip")
	cmd.Flags().StringVar(&bodyRequestDataSenderDomain, "request-data-sender-domain", "", "Sender domain")
	cmd.Flags().StringVar(&bodyRequestDataSenderDomainMatching, "request-data-sender-domain-matching", "", "An enumeration.")
	cmd.Flags().StringVar(&bodyRequestDataSenderEmail, "request-data-sender-email", "", "Sender email")
	cmd.Flags().StringVar(&bodyRequestDataSenderEmailMatching, "request-data-sender-email-matching", "", "An enumeration.")
	cmd.Flags().StringVar(&bodyRequestDataSenderIp, "request-data-sender-ip", "", "Sender ip")
	cmd.Flags().StringVar(&bodyRequestDataSenderName, "request-data-sender-name", "", "Sender name")
	cmd.Flags().StringVar(&bodyRequestDataSenderNameMatching, "request-data-sender-name-matching", "", "An enumeration.")
	cmd.Flags().StringVar(&bodyRequestDataSubject, "request-data-subject", "", "Subject")
	cmd.Flags().StringVar(&bodyRequestDataSubjectMatching, "request-data-subject-matching", "", "An enumeration.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
