// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newExceptionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "exceptions",
		Short:       "Get, create, and update exceptions",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newExceptionsCreateCmd(flags))
	cmd.AddCommand(newExceptionsCreateWhitelistCmd(flags))
	cmd.AddCommand(newExceptionsGetApCmd(flags))
	cmd.AddCommand(newExceptionsGetApExctypeCmd(flags))
	cmd.AddCommand(newExceptionsUpdateCmd(flags))
	cmd.AddCommand(newExceptionsUpdateWhitelistCmd(flags))
	cmd.AddCommand(newExceptionsDeleteCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelExceptionsAuditCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelExceptionsFindCmd(flags))
	return cmd
}
