// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// learn_init.go is the spec-driven init shim for the self-learning loop.
// newLearnConfig builds the per-CLI *entities.Config the cobra teach /
// recall / learnings commands thread through every call site;
// initLearn seeds the entity_lookups table from the canonical-+-aliases
// table declared in spec.Learn.EntityLookupSeeds. Both run once at
// startup; subsequent calls are idempotent (INSERT OR IGNORE on the
// store side, fresh Config build on the registration side).
//
// Soft validation: a runtime regex compile failure (which spec parse
// already rejects at load time) logs to stderr and continues without
// the pattern instead of aborting the CLI. Empty Learn config produces
// a Config with built-in stopwords and a no-op initLearn.

package cli

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"sync"

	"avanan-pp-cli/internal/learn/entities"
	"avanan-pp-cli/internal/learn/lookups"
	"avanan-pp-cli/internal/store"
)

// newLearnConfig returns the per-CLI entity extractor Config the
// teach / recall / normalize call sites pass into the learn package.
// Reads the printed-CLI's spec.Learn.TickerPatterns, Stopwords, and
// Synonyms; patterns that fail to compile at runtime (defense in
// depth — spec parse already validated them) log a warning and are
// skipped. Declared synonyms register on both the returned Config and
// the store package's write-side normalizer.
func newLearnConfig() *entities.Config {
	cfg := entities.NewConfig()
	// Spec-declared same-referent synonym folds, registered on BOTH
	// normalizers: the entities.Config drives the read side (recall
	// family keys) and store.RegisterQuerySynonyms the write side
	// (teach query patterns). One map, two registrations — the
	// two-normalizer symmetry the learn loop's key space depends on.
	learnSynonyms := map[string]string{
		"allow list":  "whitelist",
		"allowlist":   "whitelist",
		"blocklist":   "blacklist",
		"customer":    "scope",
		"deny list":   "blacklist",
		"denylist":    "blacklist",
		"most recent": "latest",
		"tenant":      "scope",
	}
	cfg.RegisterSynonyms(learnSynonyms)
	store.RegisterQuerySynonyms(learnSynonyms)
	return cfg
}

// initLearn seeds the entity_lookups table from the spec.Learn.
// EntityLookupSeeds declaration. INSERT OR IGNORE on the store side
// makes this idempotent — calling it twice produces the same DB state
// as calling it once. An empty seed map is a no-op (returns nil).
func initLearn(ctx context.Context, db *sql.DB) error {
	_ = ctx
	seeds := map[string][]lookups.SeedConfig{
		"action": {
			{Canonical: "quarantine", Values: []string{"remove", "pull", "block", "isolate"}},
			{Canonical: "restore", Values: []string{"release", "deliver", "un-quarantine", "unquarantine"}},
		},
		"event_state": {
			{Canonical: "new", Values: []string{"unhandled", "untriaged"}},
			{Canonical: "detected", Values: []string{"open"}},
			{Canonical: "pending", Values: []string{"in progress", "in flight"}},
			{Canonical: "remediated", Values: []string{"fixed", "handled", "quarantined and done"}},
			{Canonical: "dismissed", Values: []string{"ignored", "closed", "false positive"}},
			{Canonical: "exception", Values: []string{"excepted", "allowlisted"}},
		},
		"event_type": {
			{Canonical: "phishing", Values: []string{"phish", "phishing email", "credential harvesting"}},
			{Canonical: "malware", Values: []string{"virus", "malicious attachment"}},
			{Canonical: "suspicious malware", Values: []string{"suspected malware", "maybe malware"}},
			{Canonical: "dlp", Values: []string{"data loss", "data leak", "leak prevention"}},
			{Canonical: "anomaly", Values: []string{"anomalous", "unusual behavior"}},
			{Canonical: "shadow_it", Values: []string{"shadow it", "unsanctioned app"}},
			{Canonical: "malicious_url_click", Values: []string{"url click", "clicked link", "click time"}},
			{Canonical: "malicious_url", Values: []string{"bad url", "malicious link"}},
			{Canonical: "alert", Values: []string{"alerts"}},
		},
		"saas": {
			{Canonical: "office365_emails", Values: []string{"o365", "office 365", "outlook", "exchange", "microsoft mail"}},
			{Canonical: "google_mail", Values: []string{"gmail", "google workspace mail", "gsuite mail"}},
			{Canonical: "office365_onedrive", Values: []string{"onedrive", "one drive"}},
			{Canonical: "office365_sharepoint", Values: []string{"sharepoint", "share point"}},
			{Canonical: "google_drive", Values: []string{"gdrive", "drive"}},
			{Canonical: "ms_teams", Values: []string{"teams", "microsoft teams"}},
			{Canonical: "slack", Values: []string{"slack messages"}},
			{Canonical: "box2", Values: []string{"box"}},
			{Canonical: "dropbox2", Values: []string{"dropbox"}},
			{Canonical: "sharefile", Values: []string{"citrix sharefile", "share file"}},
			{Canonical: "email", Values: []string{"mail", "all email"}},
		},
		"sectool": {
			{Canonical: "checkpoint2", Values: []string{"anti-malware", "antimalware", "malware engine", "av"}},
			{Canonical: "avanan_url", Values: []string{"url reputation", "url rep", "link reputation"}},
			{Canonical: "avanan_dlp", Values: []string{"dlp engine", "data loss prevention"}},
			{Canonical: "anomaly", Values: []string{"anomaly engine"}},
			{Canonical: "click_time_protection", Values: []string{"ctp", "click time", "click-time protection", "safe links"}},
		},
	}
	if _, err := lookups.SeedFromConfig(db, seeds); err != nil {
		return fmt.Errorf("initLearn: seed entity_lookups: %w", err)
	}
	return nil
}

// learnInitOnce gates runLearnInitOnce so the seed pass happens at
// most once per CLI process. The sync.Once keeps the cost off the
// hot path for repeat command invocations within an MCP session.
var learnInitOnce sync.Once

// runLearnInitOnce opens the canonical store path, fires initLearn
// once per process, and downgrades any failure to a stderr warning.
// Per the self-learning loop's soft-validation contract, a seed
// failure must never abort the CLI — the recall path returns the
// empty envelope if entity_lookups is missing rows, which is the
// same behavior an opt-out CLI sees.
func runLearnInitOnce(ctx context.Context) {
	learnInitOnce.Do(func() {
		dbPath := defaultDBPath("avanan-cli")
		s, err := store.OpenWithContext(ctx, dbPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: avanan-cli: learn init: open store: %v\n", err)
			return
		}
		defer s.Close()
		if err := initLearn(ctx, s.DB()); err != nil {
			fmt.Fprintf(os.Stderr, "warning: avanan-cli: learn init: %v\n", err)
		}
	})
}
