// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMspCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "msp",
		Short:       "List, describe, create, update, and delete msp",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMspCreateCmd(flags))
	cmd.AddCommand(newMspCreateTenantsCmd(flags))
	cmd.AddCommand(newMspCreateUsersCmd(flags))
	cmd.AddCommand(newMspDeleteCmd(flags))
	cmd.AddCommand(newMspDeleteTenantsCmd(flags))
	cmd.AddCommand(newMspDeleteUsersCmd(flags))
	cmd.AddCommand(newMspDescribeTenantCmd(flags))
	cmd.AddCommand(newMspDescribeUserCmd(flags))
	cmd.AddCommand(newMspListCmd(flags))
	cmd.AddCommand(newMspListAddonsCmd(flags))
	cmd.AddCommand(newMspListDailyUsagesCmd(flags))
	cmd.AddCommand(newMspListLicensesCmd(flags))
	cmd.AddCommand(newMspListMonthlyUsagesCmd(flags))
	cmd.AddCommand(newMspListTenantsCmd(flags))
	cmd.AddCommand(newMspListUsersCmd(flags))
	cmd.AddCommand(newMspUpdateCmd(flags))
	cmd.AddCommand(newMspUpdateOrCreateTenantLicenseCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelMspFleetCmd(flags))
	return cmd
}
