// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/spf13/cobra"
)

func newMspCreateUsersCmd(flags *rootFlags) *cobra.Command {
	var flagMspName string
	var flagXAvReqId string
	var bodyRequestDataMSPId int
	var bodyRequestDataDirectLogin string
	var bodyRequestDataEmail string
	var bodyRequestDataFirstName string
	var bodyRequestDataLastName string
	var bodyRequestDataReceiveWeeklyReports string
	var bodyRequestDataRole string
	var bodyRequestDataSamlLogin string
	var bodyRequestDataSendAlerts string
	var bodyRequestDataViewPrivateData string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-users",
		Short:       "Create User.",
		Example:     "  avanan-cli msp create-users --msp-name example-resource --x-av-req-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "msp.create-users", "pp:method": "POST", "pp:path": "/v1.0/msp/users"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !cmd.Flags().Changed("msp-name") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "msp-name")
			}
			if !stdinBody {
				if !cmd.Flags().Changed("request-data-direct-login") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-direct-login")
				}
				if !cmd.Flags().Changed("request-data-email") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-email")
				}
				if !cmd.Flags().Changed("request-data-first-name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-first-name")
				}
				if !cmd.Flags().Changed("request-data-last-name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-last-name")
				}
				if !cmd.Flags().Changed("request-data-receive-weekly-reports") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-receive-weekly-reports")
				}
				if !cmd.Flags().Changed("request-data-role") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-role")
				}
				if !cmd.Flags().Changed("request-data-saml-login") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-saml-login")
				}
				if !cmd.Flags().Changed("request-data-send-alerts") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-send-alerts")
				}
				if !cmd.Flags().Changed("request-data-view-private-data") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "request-data-view-private-data")
				}
			}
			path := "/v1.0/msp/users"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			headerOverrides := map[string]string{}

			if cmd.Flags().Changed("msp-name") || flagMspName != "" {
				headerOverrides["msp_name"] = formatCLIParamValue(flagMspName)
			}

			if cmd.Flags().Changed("x-av-req-id") || flagXAvReqId != "" {
				headerOverrides["x-av-req-id"] = formatCLIParamValue(flagXAvReqId)
			}

			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				{
					nestedRequestData := map[string]any{}
					if cmd.Flags().Changed("request-data-msp-id") || bodyRequestDataMSPId != 0 {
						nestedRequestData["MSPId"] = bodyRequestDataMSPId
					}
					if cmd.Flags().Changed("request-data-direct-login") || bodyRequestDataDirectLogin != "" {
						parsedRequestDataDirectLogin, err := strconv.ParseBool(bodyRequestDataDirectLogin)
						if err != nil {
							return fmt.Errorf("parsing --request-data-direct-login as bool: %w", err)
						}
						nestedRequestData["directLogin"] = parsedRequestDataDirectLogin
					}
					if cmd.Flags().Changed("request-data-email") || bodyRequestDataEmail != "" {
						nestedRequestData["email"] = bodyRequestDataEmail
					}
					if cmd.Flags().Changed("request-data-first-name") || bodyRequestDataFirstName != "" {
						nestedRequestData["firstName"] = bodyRequestDataFirstName
					}
					if cmd.Flags().Changed("request-data-last-name") || bodyRequestDataLastName != "" {
						nestedRequestData["lastName"] = bodyRequestDataLastName
					}
					if cmd.Flags().Changed("request-data-receive-weekly-reports") || bodyRequestDataReceiveWeeklyReports != "" {
						parsedRequestDataReceiveWeeklyReports, err := strconv.ParseBool(bodyRequestDataReceiveWeeklyReports)
						if err != nil {
							return fmt.Errorf("parsing --request-data-receive-weekly-reports as bool: %w", err)
						}
						nestedRequestData["receiveWeeklyReports"] = parsedRequestDataReceiveWeeklyReports
					}
					if cmd.Flags().Changed("request-data-role") || bodyRequestDataRole != "" {
						nestedRequestData["role"] = bodyRequestDataRole
					}
					if cmd.Flags().Changed("request-data-saml-login") || bodyRequestDataSamlLogin != "" {
						parsedRequestDataSamlLogin, err := strconv.ParseBool(bodyRequestDataSamlLogin)
						if err != nil {
							return fmt.Errorf("parsing --request-data-saml-login as bool: %w", err)
						}
						nestedRequestData["samlLogin"] = parsedRequestDataSamlLogin
					}
					if cmd.Flags().Changed("request-data-send-alerts") || bodyRequestDataSendAlerts != "" {
						parsedRequestDataSendAlerts, err := strconv.ParseBool(bodyRequestDataSendAlerts)
						if err != nil {
							return fmt.Errorf("parsing --request-data-send-alerts as bool: %w", err)
						}
						nestedRequestData["sendAlerts"] = parsedRequestDataSendAlerts
					}
					if cmd.Flags().Changed("request-data-view-private-data") || bodyRequestDataViewPrivateData != "" {
						parsedRequestDataViewPrivateData, err := strconv.ParseBool(bodyRequestDataViewPrivateData)
						if err != nil {
							return fmt.Errorf("parsing --request-data-view-private-data as bool: %w", err)
						}
						nestedRequestData["viewPrivateData"] = parsedRequestDataViewPrivateData
					}
					if len(nestedRequestData) > 0 {
						bodyMap["requestData"] = nestedRequestData
					}
				}
			}
			data, statusCode, err := c.PostWithParamsAndHeaders(cmd.Context(), path, params, body, headerOverrides)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "msp", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "msp", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "msp", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "msp", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "msp", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "msp",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "msp", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "msp", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&flagMspName, "msp-name", "", "Msp name")
	cmd.Flags().StringVar(&flagXAvReqId, "x-av-req-id", "", "X av req id")
	cmd.Flags().IntVar(&bodyRequestDataMSPId, "request-data-msp-id", 0, "Mspid")
	cmd.Flags().StringVar(&bodyRequestDataDirectLogin, "request-data-direct-login", "", "Direct login")
	cmd.Flags().StringVar(&bodyRequestDataEmail, "request-data-email", "", "Email")
	cmd.Flags().StringVar(&bodyRequestDataFirstName, "request-data-first-name", "", "First name")
	cmd.Flags().StringVar(&bodyRequestDataLastName, "request-data-last-name", "", "Last name")
	cmd.Flags().StringVar(&bodyRequestDataReceiveWeeklyReports, "request-data-receive-weekly-reports", "", "Receive weekly reports")
	cmd.Flags().StringVar(&bodyRequestDataRole, "request-data-role", "", "Role")
	cmd.Flags().StringVar(&bodyRequestDataSamlLogin, "request-data-saml-login", "", "Saml login")
	cmd.Flags().StringVar(&bodyRequestDataSendAlerts, "request-data-send-alerts", "", "Send alerts")
	cmd.Flags().StringVar(&bodyRequestDataViewPrivateData, "request-data-view-private-data", "", "View private data")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
