// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"avanan-pp-cli/internal/cliutil"
	"github.com/spf13/cobra"
)

func newReportPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagScope string
	var bodyRequestDataClassification string
	var bodyRequestDataConfident string
	var bodyRequestDataEntityIds string

	cmd := &cobra.Command{
		Use:         "report",
		Short:       "Report that one or more entities were mis-classified (phishing, spam, clean, or marketing email).",
		Long:        "Report that one or more entities were mis-classified (phishing, spam, clean, or marketing email).",
		Example:     "  avanan-cli report",
		Annotations: map[string]string{"pp:endpoint": "report.post-mis-classification", "pp:method": "POST", "pp:path": "/v1.0/report/mis-classification"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !cmd.Flags().Changed("request-data-classification") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "request-data-classification")
			}
			if !cmd.Flags().Changed("request-data-entity-ids") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "request-data-entity-ids")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1.0/report/mis-classification"
			params := map[string]string{}
			if cmd.Flags().Changed("scope") || flagScope != "" {
				params["scope"] = formatCLIParamValue(flagScope)
			}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			bodyMap := map[string]any{}
			var body any = bodyMap
			{
				nestedRequestData := map[string]any{}
				if cmd.Flags().Changed("request-data-classification") || bodyRequestDataClassification != "" {
					nestedRequestData["classification"] = bodyRequestDataClassification
				}
				if cmd.Flags().Changed("request-data-confident") || bodyRequestDataConfident != "" {
					nestedRequestData["confident"] = bodyRequestDataConfident
				}
				if cmd.Flags().Changed("request-data-entity-ids") {
					parsedRequestDataEntityIds, parseErr := cliutil.ParseStringList(bodyRequestDataEntityIds)
					if parseErr != nil {
						return fmt.Errorf("parsing --request-data-entity-ids list: %w", parseErr)
					}
					nestedRequestData["entityIds"] = parsedRequestDataEntityIds
				}
				if len(nestedRequestData) > 0 {
					bodyMap["requestData"] = nestedRequestData
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "report", data, "")
			}
			outputData := data
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(outputData, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{outputData}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagScope, "scope", "", "Single {farm}:{tenant} scope. Required when the app client is bound to more than one tenant.")
	cmd.Flags().StringVar(&bodyRequestDataClassification, "request-data-classification", "", "The classification the message should have received.")
	cmd.Flags().StringVar(&bodyRequestDataConfident, "request-data-confident", "", "Reporter confidence, as accepted by the API.")
	cmd.Flags().StringVar(&bodyRequestDataEntityIds, "request-data-entity-ids", "", "SaaS entity IDs being reported.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
