// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDownloadPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagOriginal bool
	var flagScopes string

	cmd := &cobra.Command{
		Use:         "download <entity_id>",
		Short:       "Download the raw .eml for a SaaS entity.",
		Long:        "Download the raw .eml for a SaaS entity.",
		Example:     "  avanan-cli download 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "download.get-entity", "pp:method": "GET", "pp:path": "/v1.0/download/entity/{entity_id}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1.0/download/entity/{entity_id}"
			if len(args) < 1 || args[0] == "" {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "entity_id is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "entity_id"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("entity_id is required\nUsage: %s <%s>", cmd.CommandPath(), "entity_id"))
			}
			path = replacePathParam(path, "entity_id", args[0])
			headerOverrides := map[string]string{
				"Accept":                           "application/octet-stream",
				"X-Printing-Press-Binary-Response": "true",
			}

			params := map[string]string{}
			if flagOriginal != false {
				params["original"] = formatCLIParamValue(flagOriginal)
			}
			if flagScopes != "" {
				params["scopes"] = formatCLIParamValue(flagScopes)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "download", false, path, params, headerOverrides, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			_ = os.Stderr
			_ = prov
			if flags.quiet {
				return nil
			}
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				var envelope struct {
					PPBinary bool   `json:"_pp_binary"`
					Encoding string `json:"encoding"`
				}
				if err := json.Unmarshal(data, &envelope); err != nil || !envelope.PPBinary || envelope.Encoding != "base64" {
					return fmt.Errorf("binary response cannot be rendered as structured output; redirect stdout or use --deliver file:<path>")
				}
				if flags.csv {
					data = append(append(json.RawMessage{'['}, data...), ']')
				}
				return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
			}
			_, err = cmd.OutOrStdout().Write(data)
			return err
		},
	}
	cmd.Flags().BoolVar(&flagOriginal, "original", false, "true downloads the original message unmodified; false (default) adds Avanan security headers.")
	cmd.Flags().StringVar(&flagScopes, "scopes", "", "Comma-separated {farm}:{tenant} scopes to target.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
