// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSectoolExceptionsExceptionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "exceptions",
		Short:       "List, get, create, and delete exceptions for sectool exceptions",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSectoolExceptionsExceptionsCreateSectoolEntryCmd(flags))
	cmd.AddCommand(newSectoolExceptionsExceptionsDeleteSectoolEntriesCmd(flags))
	cmd.AddCommand(newSectoolExceptionsExceptionsGetSectoolCmd(flags))
	cmd.AddCommand(newSectoolExceptionsExceptionsListSectoolCmd(flags))
	return cmd
}
