// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSectoolsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "sectools",
		Short:       "List, get, create, update, and delete sectools",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSectoolsCreateAnomalyExceptionCmd(flags))
	cmd.AddCommand(newSectoolsCreateCtpItemCmd(flags))
	cmd.AddCommand(newSectoolsDeleteAnomalyExceptionsCmd(flags))
	cmd.AddCommand(newSectoolsDeleteCtpItemCmd(flags))
	cmd.AddCommand(newSectoolsDeleteCtpItemsCmd(flags))
	cmd.AddCommand(newSectoolsDeleteCtpListsCmd(flags))
	cmd.AddCommand(newSectoolsGetCtpItemCmd(flags))
	cmd.AddCommand(newSectoolsGetCtpListCmd(flags))
	cmd.AddCommand(newSectoolsListAnomalyExceptionsCmd(flags))
	cmd.AddCommand(newSectoolsListCtpItemsCmd(flags))
	cmd.AddCommand(newSectoolsListCtpListsCmd(flags))
	cmd.AddCommand(newSectoolsUpdateCtpItemCmd(flags))
	cmd.AddCommand(newSectoolsUpdateCtpItemsCmd(flags))
	return cmd
}
