// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSoarCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "soar",
		Short:       "Get and create soar",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSoarGetEntityCmd(flags))
	cmd.AddCommand(newSoarPostNotifyCmd(flags))
	return cmd
}
