// Copyright 2026 geekbrownbear and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Three tools cover the entire API: <api>_search to discover endpoints,
// <api>_get to inspect one GET endpoint, and <api>_execute to invoke one.
// This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search, get, and execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	neturl "net/url"
	"sort"
	"strings"

	"avanan-pp-cli/internal/cli"
	"avanan-pp-cli/internal/mcp/bound"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the agent-facing tools that cover
// the whole API surface. Called from RegisterTools in place of the per-endpoint
// registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("avanan_search",
			mcplib.WithDescription("Search the avanan API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(false),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("avanan_get",
			mcplib.WithDescription("Get metadata for one GET endpoint by its endpoint_id (from avanan_search). This registry-only lookup never calls the API."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("GET endpoint identifier returned by avanan_search (e.g., \"users.list\").")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(false),
		),
		handleCodeOrchGet,
	)

	s.AddTool(
		mcplib.NewTool("avanan_execute",
			mcplib.WithDescription("Execute one avanan API endpoint by its endpoint_id (from avanan_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by avanan_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// registry tools need at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	// TemplateParams carries public-to-wire bindings for promoted global path
	// placeholders. These resolve through Config.TemplateVars just like the
	// per-endpoint MCP tool inputs do.
	TemplateParams []codeOrchParamBinding
	// QueryParams carries public-to-wire bindings for spec-declared in:query
	// parameters. Write methods (POST/PUT/PATCH) route these to the query
	// string instead of dumping them into the JSON body. Derived from the
	// same mcpParamBindings location data the per-endpoint tools use.
	QueryParams []codeOrchParamBinding
	// Keep declared headers out of query/body routing so execution sends them
	// through the request-header map.
	HeaderParams []codeOrchParamBinding
	// HeaderOverrides carries per-endpoint request headers (e.g. an
	// Accept override for binary-only response endpoints). Without
	// threading these through, the code-orchestration execute path
	// sends the client's default Accept and binary endpoints 406.
	HeaderOverrides map[string]string
	// BodyIsArray marks endpoints whose request body schema root is a
	// bare top-level JSON array. The execute path then sends a top-level
	// array (the agent supplies it as params["body"]) instead of the
	// params object; a strict-mapping API rejects an object at the body
	// root with HTTP 422 "Invalid json".
	BodyIsArray bool
	Mutating    bool
	keywords    []string
}

type codeOrchParamBinding struct {
	PublicName   string
	WireName     string
	Default      string
	QueryArray   bool
	QueryStyle   string
	QueryExplode bool
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:             "action.post-entity",
		Method:         "POST",
		Path:           "/v1.0/action/entity",
		Summary:        "Post Entity Action.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("action", "post-entity", "Post Entity Action.", "/v1.0/action/entity"),
	},
	{
		ID:             "action.post-event",
		Method:         "POST",
		Path:           "/v1.0/action/event",
		Summary:        "Post Event Action.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("action", "post-event", "Post Event Action.", "/v1.0/action/event"),
	},
	{
		ID:             "avanan-search.get-saas-entity",
		Method:         "GET",
		Path:           "/v1.0/search/entity/{entity_id}",
		Summary:        "Get Saas Entity.",
		Positional:     []string{"entity_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("avanan-search", "get-saas-entity", "Get Saas Entity.", "/v1.0/search/entity/{entity_id}"),
	},
	{
		ID:             "avanan-search.query-saas-entity",
		Method:         "POST",
		Path:           "/v1.0/search/query",
		Summary:        "Query Saas Entity.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("avanan-search", "query-saas-entity", "Query Saas Entity.", "/v1.0/search/query"),
	},
	{
		ID:              "download.get-entity",
		Method:          "GET",
		Path:            "/v1.0/download/entity/{entity_id}",
		Summary:         "Download the raw .eml for a SaaS entity.",
		Positional:      []string{"entity_id"},
		TemplateParams:  []codeOrchParamBinding{},
		QueryParams:     []codeOrchParamBinding{{PublicName: "original", WireName: "original"}, {PublicName: "scopes", WireName: "scopes"}},
		HeaderParams:    []codeOrchParamBinding{},
		Mutating:        false,
		HeaderOverrides: map[string]string{"Accept": "application/octet-stream"},
		keywords:        codeOrchKeywords("download", "get-entity", "Download the raw .eml for a SaaS entity.", "/v1.0/download/entity/{entity_id}"),
	},
	{
		ID:             "download-large-email.get-url",
		Method:         "GET",
		Path:           "/v1.0/download_large_email/entity/{entity_id}",
		Summary:        "Return a presigned URL for downloading a message too large to stream inline.",
		Positional:     []string{"entity_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("download-large-email", "get-url", "Return a presigned URL for downloading a message too large to stream inline.", "/v1.0/download_large_email/entity/{entity_id}"),
	},
	{
		ID:             "event.get",
		Method:         "GET",
		Path:           "/v1.0/event/{event_id}",
		Summary:        "Get Event.",
		Positional:     []string{"event_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("event", "get", "Get Event.", "/v1.0/event/{event_id}"),
	},
	{
		ID:             "event.query",
		Method:         "POST",
		Path:           "/v1.0/event/query",
		Summary:        "Query Event.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("event", "query", "Query Event.", "/v1.0/event/query"),
	},
	{
		ID:             "exceptions.create",
		Method:         "POST",
		Path:           "/v1.0/exceptions/blacklist",
		Summary:        "Create Ap Exception Blacklist.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("exceptions", "create", "Create Ap Exception Blacklist.", "/v1.0/exceptions/blacklist"),
	},
	{
		ID:             "exceptions.create-whitelist",
		Method:         "POST",
		Path:           "/v1.0/exceptions/whitelist",
		Summary:        "Create Ap Exception Whitelist.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("exceptions", "create-whitelist", "Create Ap Exception Whitelist.", "/v1.0/exceptions/whitelist"),
	},
	{
		ID:             "exceptions.get-ap",
		Method:         "GET",
		Path:           "/v1.0/exceptions/{exc_type}",
		Summary:        "Get Ap Exception.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "exc_id", WireName: "exc_id"}, {PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("exceptions", "get-ap", "Get Ap Exception.", "/v1.0/exceptions/{exc_type}"),
	},
	{
		ID:             "exceptions.get-ap-exctype",
		Method:         "GET",
		Path:           "/v1.0/exceptions/{exc_type}/{exc_id}",
		Summary:        "Get Ap Exception.",
		Positional:     []string{"exc_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("exceptions", "get-ap-exctype", "Get Ap Exception.", "/v1.0/exceptions/{exc_type}/{exc_id}"),
	},
	{
		ID:             "exceptions.update",
		Method:         "PUT",
		Path:           "/v1.0/exceptions/blacklist/{exc_id}",
		Summary:        "Update Ap Exception Blacklist.",
		Positional:     []string{"exc_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("exceptions", "update", "Update Ap Exception Blacklist.", "/v1.0/exceptions/blacklist/{exc_id}"),
	},
	{
		ID:             "exceptions.update-whitelist",
		Method:         "PUT",
		Path:           "/v1.0/exceptions/whitelist/{exc_id}",
		Summary:        "Update Ap Exception Whitelist.",
		Positional:     []string{"exc_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("exceptions", "update-whitelist", "Update Ap Exception Whitelist.", "/v1.0/exceptions/whitelist/{exc_id}"),
	},
	{
		ID:             "exceptions.delete.ap-exception",
		Method:         "POST",
		Path:           "/v1.0/exceptions/{exc_type}/delete/{exc_id}",
		Summary:        "Delete Ap Exception.",
		Positional:     []string{"exc_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("exceptions", "ap-exception", "Delete Ap Exception.", "/v1.0/exceptions/{exc_type}/delete/{exc_id}"),
	},
	{
		ID:             "msp.create",
		Method:         "POST",
		Path:           "/v1.0/msp/msp-partners",
		Summary:        "Create Msp.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "create", "Create Msp.", "/v1.0/msp/msp-partners"),
	},
	{
		ID:             "msp.create-tenants",
		Method:         "POST",
		Path:           "/v1.0/msp/tenants",
		Summary:        "Create Tenant.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "create-tenants", "Create Tenant.", "/v1.0/msp/tenants"),
	},
	{
		ID:             "msp.create-users",
		Method:         "POST",
		Path:           "/v1.0/msp/users",
		Summary:        "Create User.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "create-users", "Create User.", "/v1.0/msp/users"),
	},
	{
		ID:             "msp.delete",
		Method:         "DELETE",
		Path:           "/v1.0/msp/msp-partners/{msp_id}",
		Summary:        "Delete Msp.",
		Positional:     []string{"msp_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "delete", "Delete Msp.", "/v1.0/msp/msp-partners/{msp_id}"),
	},
	{
		ID:             "msp.delete-tenants",
		Method:         "DELETE",
		Path:           "/v1.0/msp/tenants/{tenant_id}",
		Summary:        "Delete Tenant.",
		Positional:     []string{"tenant_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "delete-tenants", "Delete Tenant.", "/v1.0/msp/tenants/{tenant_id}"),
	},
	{
		ID:             "msp.delete-users",
		Method:         "DELETE",
		Path:           "/v1.0/msp/users/{user_id}",
		Summary:        "Delete User.",
		Positional:     []string{"user_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "delete-users", "Delete User.", "/v1.0/msp/users/{user_id}"),
	},
	{
		ID:             "msp.describe-tenant",
		Method:         "GET",
		Path:           "/v1.0/msp/tenants/{tenant_id}",
		Summary:        "Describe Tenant.",
		Positional:     []string{"tenant_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "describe-tenant", "Describe Tenant.", "/v1.0/msp/tenants/{tenant_id}"),
	},
	{
		ID:             "msp.describe-user",
		Method:         "GET",
		Path:           "/v1.0/msp/users/{user_id}",
		Summary:        "Describe User.",
		Positional:     []string{"user_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "describe-user", "Describe User.", "/v1.0/msp/users/{user_id}"),
	},
	{
		ID:             "msp.list",
		Method:         "GET",
		Path:           "/v1.0/msp/msp-partners",
		Summary:        "List Msps.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "list", "List Msps.", "/v1.0/msp/msp-partners"),
	},
	{
		ID:             "msp.list-addons",
		Method:         "GET",
		Path:           "/v1.0/msp/addons",
		Summary:        "List Addons.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "list-addons", "List Addons.", "/v1.0/msp/addons"),
	},
	{
		ID:             "msp.list-daily-usages",
		Method:         "GET",
		Path:           "/v1.0/msp/usage/day",
		Summary:        "List Daily Usages.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "year", WireName: "year"}, {PublicName: "month", WireName: "month"}, {PublicName: "day", WireName: "day"}, {PublicName: "msp_ids", WireName: "msp_ids", QueryArray: true, QueryStyle: "form", QueryExplode: true}},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "list-daily-usages", "List Daily Usages.", "/v1.0/msp/usage/day"),
	},
	{
		ID:             "msp.list-licenses",
		Method:         "GET",
		Path:           "/v1.0/msp/licenses",
		Summary:        "List Licenses.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "list-licenses", "List Licenses.", "/v1.0/msp/licenses"),
	},
	{
		ID:             "msp.list-monthly-usages",
		Method:         "GET",
		Path:           "/v1.0/msp/usage",
		Summary:        "List Monthly Usages.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "year", WireName: "year"}, {PublicName: "month", WireName: "month"}, {PublicName: "msp_ids", WireName: "msp_ids", QueryArray: true, QueryStyle: "form", QueryExplode: true}},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "list-monthly-usages", "List Monthly Usages.", "/v1.0/msp/usage"),
	},
	{
		ID:             "msp.list-tenants",
		Method:         "GET",
		Path:           "/v1.0/msp/tenants",
		Summary:        "List Tenants.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "list-tenants", "List Tenants.", "/v1.0/msp/tenants"),
	},
	{
		ID:             "msp.list-users",
		Method:         "GET",
		Path:           "/v1.0/msp/users",
		Summary:        "List Users.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "list-users", "List Users.", "/v1.0/msp/users"),
	},
	{
		ID:             "msp.update",
		Method:         "PUT",
		Path:           "/v1.0/msp/users/{user_id}",
		Summary:        "Update User.",
		Positional:     []string{"user_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "update", "Update User.", "/v1.0/msp/users/{user_id}"),
	},
	{
		ID:             "msp.update-or-create-tenant-license",
		Method:         "POST",
		Path:           "/v1.0/msp/tenants/{tenant_id}/license",
		Summary:        "Update Or Create Tenant License.",
		Positional:     []string{"tenant_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "msp_name", WireName: "msp_name"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("msp", "update-or-create-tenant-license", "Update Or Create Tenant License.", "/v1.0/msp/tenants/{tenant_id}/license"),
	},
	{
		ID:             "report.post-mis-classification",
		Method:         "POST",
		Path:           "/v1.0/report/mis-classification",
		Summary:        "Report that one or more entities were mis-classified (phishing, spam, clean, or marketing email).",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("report", "post-mis-classification", "Report that one or more entities were mis-classified (phishing, spam, clean, or marketing email).", "/v1.0/report/mis-classification"),
	},
	{
		ID:             "scopes.get",
		Method:         "GET",
		Path:           "/v1.0/scopes",
		Summary:        "Get Scopes.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("scopes", "get", "Get Scopes.", "/v1.0/scopes"),
	},
	{
		ID:             "sectool-exceptions.create",
		Method:         "POST",
		Path:           "/v1.0/sectool-exceptions/{sectool}",
		Summary:        "Create an exception for the named security engine.",
		Positional:     []string{"sectool"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectool-exceptions", "create", "Create an exception for the named security engine.", "/v1.0/sectool-exceptions/{sectool}"),
	},
	{
		ID:             "sectool-exceptions.delete",
		Method:         "DELETE",
		Path:           "/v1.0/sectool-exceptions/{sectool}",
		Summary:        "Delete an exception for the named security engine.",
		Positional:     []string{"sectool"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectool-exceptions", "delete", "Delete an exception for the named security engine.", "/v1.0/sectool-exceptions/{sectool}"),
	},
	{
		ID:             "sectool-exceptions.update",
		Method:         "PUT",
		Path:           "/v1.0/sectool-exceptions/{sectool}",
		Summary:        "Update an existing exception for the named security engine.",
		Positional:     []string{"sectool"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectool-exceptions", "update", "Update an existing exception for the named security engine.", "/v1.0/sectool-exceptions/{sectool}"),
	},
	{
		ID:             "sectool-exceptions.exceptions.create-sectool-entry",
		Method:         "POST",
		Path:           "/v1.0/sectool-exceptions/{sectool}/exceptions",
		Summary:        "Create a typed exception entry for the named security engine.",
		Positional:     []string{"sectool"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectool-exceptions", "create-sectool-entry", "Create a typed exception entry for the named security engine.", "/v1.0/sectool-exceptions/{sectool}/exceptions"),
	},
	{
		ID:             "sectool-exceptions.exceptions.delete-sectool-entries",
		Method:         "DELETE",
		Path:           "/v1.0/sectool-exceptions/{sectool}/exceptions",
		Summary:        "Delete multiple typed exception entries for the named security engine.",
		Positional:     []string{"sectool"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectool-exceptions", "delete-sectool-entries", "Delete multiple typed exception entries for the named security engine.", "/v1.0/sectool-exceptions/{sectool}/exceptions"),
	},
	{
		ID:             "sectool-exceptions.exceptions.get-sectool",
		Method:         "GET",
		Path:           "/v1.0/sectool-exceptions/{sectool}/exceptions/{exception_type}/{exceptions_str}",
		Summary:        "Get one exception by its match string — a file hash, text fragment, sender address, recipient address, URL, or domain.",
		Positional:     []string{"sectool", "exception_type", "exceptions_str"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectool-exceptions", "get-sectool", "Get one exception by its match string — a file hash, text fragment, sender address, recipient address, URL, or domain.", "/v1.0/sectool-exceptions/{sectool}/exceptions/{exception_type}/{exceptions_str}"),
	},
	{
		ID:             "sectool-exceptions.exceptions.list-sectool",
		Method:         "GET",
		Path:           "/v1.0/sectool-exceptions/{sectool}/exceptions/{exception_type}",
		Summary:        "List every exception of the given type for the named security engine.",
		Positional:     []string{"sectool", "exception_type"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectool-exceptions", "list-sectool", "List every exception of the given type for the named security engine.", "/v1.0/sectool-exceptions/{sectool}/exceptions/{exception_type}"),
	},
	{
		ID:             "sectools.create-anomaly-exception",
		Method:         "POST",
		Path:           "/v1.0/sectools/anomaly/exceptions",
		Summary:        "Create an Anomaly engine exception rule.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "create-anomaly-exception", "Create an Anomaly engine exception rule.", "/v1.0/sectools/anomaly/exceptions"),
	},
	{
		ID:             "sectools.create-ctp-item",
		Method:         "POST",
		Path:           "/v1.0/sectools/click_time_protection/exceptions/items",
		Summary:        "Add an entry to a Click-Time Protection exception list.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "create-ctp-item", "Add an entry to a Click-Time Protection exception list.", "/v1.0/sectools/click_time_protection/exceptions/items"),
	},
	{
		ID:             "sectools.delete-anomaly-exceptions",
		Method:         "DELETE",
		Path:           "/v1.0/sectools/anomaly/exceptions",
		Summary:        "Delete Anomaly engine exception rules by rule ID.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "delete-anomaly-exceptions", "Delete Anomaly engine exception rules by rule ID.", "/v1.0/sectools/anomaly/exceptions"),
	},
	{
		ID:             "sectools.delete-ctp-item",
		Method:         "DELETE",
		Path:           "/v1.0/sectools/click_time_protection/exceptions/items/{item_id}",
		Summary:        "Delete one Click-Time Protection exception entry.",
		Positional:     []string{"item_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "delete-ctp-item", "Delete one Click-Time Protection exception entry.", "/v1.0/sectools/click_time_protection/exceptions/items/{item_id}"),
	},
	{
		ID:             "sectools.delete-ctp-items",
		Method:         "DELETE",
		Path:           "/v1.0/sectools/click_time_protection/exceptions/items",
		Summary:        "Delete multiple Click-Time Protection exception entries by ID.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "delete-ctp-items", "Delete multiple Click-Time Protection exception entries by ID.", "/v1.0/sectools/click_time_protection/exceptions/items"),
	},
	{
		ID:             "sectools.delete-ctp-lists",
		Method:         "DELETE",
		Path:           "/v1.0/sectools/click_time_protection/exceptions",
		Summary:        "Delete every Click-Time Protection exception list.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "delete-ctp-lists", "Delete every Click-Time Protection exception list.", "/v1.0/sectools/click_time_protection/exceptions"),
	},
	{
		ID:             "sectools.get-ctp-item",
		Method:         "GET",
		Path:           "/v1.0/sectools/click_time_protection/exceptions/items/{item_id}",
		Summary:        "Get one Click-Time Protection exception entry by ID.",
		Positional:     []string{"item_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "get-ctp-item", "Get one Click-Time Protection exception entry by ID.", "/v1.0/sectools/click_time_protection/exceptions/items/{item_id}"),
	},
	{
		ID:             "sectools.get-ctp-list",
		Method:         "GET",
		Path:           "/v1.0/sectools/click_time_protection/exceptions/{list_id}",
		Summary:        "Get one Click-Time Protection exception list by ID.",
		Positional:     []string{"list_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "get-ctp-list", "Get one Click-Time Protection exception list by ID.", "/v1.0/sectools/click_time_protection/exceptions/{list_id}"),
	},
	{
		ID:             "sectools.list-anomaly-exceptions",
		Method:         "GET",
		Path:           "/v1.0/sectools/anomaly/exceptions",
		Summary:        "List the Anomaly engine's exception rules.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "list-anomaly-exceptions", "List the Anomaly engine's exception rules.", "/v1.0/sectools/anomaly/exceptions"),
	},
	{
		ID:             "sectools.list-ctp-items",
		Method:         "GET",
		Path:           "/v1.0/sectools/click_time_protection/exceptions/items",
		Summary:        "List the individual entries across Click-Time Protection exception lists.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "list-ctp-items", "List the individual entries across Click-Time Protection exception lists.", "/v1.0/sectools/click_time_protection/exceptions/items"),
	},
	{
		ID:             "sectools.list-ctp-lists",
		Method:         "GET",
		Path:           "/v1.0/sectools/click_time_protection/exceptions",
		Summary:        "List the Click-Time Protection exception lists.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "list-ctp-lists", "List the Click-Time Protection exception lists.", "/v1.0/sectools/click_time_protection/exceptions"),
	},
	{
		ID:             "sectools.update-ctp-item",
		Method:         "PUT",
		Path:           "/v1.0/sectools/click_time_protection/exceptions/items/{item_id}",
		Summary:        "Update one Click-Time Protection exception entry.",
		Positional:     []string{"item_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "update-ctp-item", "Update one Click-Time Protection exception entry.", "/v1.0/sectools/click_time_protection/exceptions/items/{item_id}"),
	},
	{
		ID:             "sectools.update-ctp-items",
		Method:         "PUT",
		Path:           "/v1.0/sectools/click_time_protection/exceptions/items",
		Summary:        "Update Click-Time Protection exception list entries.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("sectools", "update-ctp-items", "Update Click-Time Protection exception list entries.", "/v1.0/sectools/click_time_protection/exceptions/items"),
	},
	{
		ID:             "soar.get-entity",
		Method:         "GET",
		Path:           "/v1.0/soar/entity/{entity_id}",
		Summary:        "Retrieve the decoded email record for a SaaS entity, including headers and body.",
		Positional:     []string{"entity_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("soar", "get-entity", "Retrieve the decoded email record for a SaaS entity, including headers and body.", "/v1.0/soar/entity/{entity_id}"),
	},
	{
		ID:             "soar.post-notify",
		Method:         "POST",
		Path:           "/v1.0/soar/notify",
		Summary:        "Send an exposure notification about a specific entity to a list of email addresses.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("soar", "post-notify", "Send an exposure notification about a specific entity to a list of email addresses.", "/v1.0/soar/notify"),
	},
	{
		ID:             "task.get",
		Method:         "GET",
		Path:           "/v1.0/task/{task_id}",
		Summary:        "Get Task.",
		Positional:     []string{"task_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "scope", WireName: "scope"}},
		HeaderParams:   []codeOrchParamBinding{{PublicName: "scopes", WireName: "scopes"}, {PublicName: "x-av-req-id", WireName: "x-av-req-id"}},
		Mutating:       false,
		keywords:       codeOrchKeywords("task", "get", "Get Task.", "/v1.0/task/{task_id}"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func codeOrchEndpointMetadata(ep *codeOrchEndpoint) map[string]any {
	out := map[string]any{
		"endpoint_id": ep.ID,
		"method":      ep.Method,
		"path":        ep.Path,
		"summary":     ep.Summary,
	}
	return out
}

func findCodeOrchEndpoint(id string) *codeOrchEndpoint {
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			return &codeOrchEndpoints[i]
		}
	}
	return nil
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		item := codeOrchEndpointMetadata(r.ep)
		item["score"] = r.score
		out = append(out, item)
	}
	text, err := bound.JSON(map[string]any{"count": len(out), "results": out})
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding search results: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleCodeOrchGet(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call avanan_search first)"), nil
	}
	ep := findCodeOrchEndpoint(id)
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call avanan_search to discover valid ids", id)), nil
	}
	if ep.Method != "GET" {
		return mcplib.NewToolResultError(fmt.Sprintf("endpoint_id %q is %s, but avanan_get only permits GET endpoints", id, ep.Method)), nil
	}
	text, err := bound.JSON(codeOrchEndpointMetadata(ep))
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding endpoint metadata: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call avanan_search first)"), nil
	}

	ep := findCodeOrchEndpoint(id)
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call avanan_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, platformSession, err := newMCPClient(ctx)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	if platformSession != nil {
		defer platformSession.ZeroCredentials()
	}
	if err := cli.AdoptMCPOutputSemantics(platformSession, params); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok && strings.Contains(path, "{"+p+"}") {
			path = strings.ReplaceAll(path, "{"+p+"}", mcpPathValue(v))
			delete(params, p)
		}
	}

	hdrs := make(map[string]string, len(ep.HeaderOverrides)+len(ep.HeaderParams))
	for k, v := range ep.HeaderOverrides {
		hdrs[k] = v
	}
	for _, binding := range ep.HeaderParams {
		if binding.Default != "" {
			hdrs[binding.WireName] = binding.Default
		}
		for _, key := range []string{binding.PublicName, binding.WireName} {
			if v, ok := params[key]; ok {
				hdrs[binding.WireName] = formatMCPParamValue(v)
				delete(params, key)
				break
			}
		}
	}
	if len(hdrs) == 0 {
		hdrs = nil
	}

	// Route params to their runtime slots. GET/DELETE params are query
	// strings; write methods split spec-declared query params from the
	// remaining params used as the request body below.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		path = codeOrchSplitQuery(path, ep.QueryParams, params)
		for k, v := range params {
			query[codeOrchWireQueryName(ep.QueryParams, k)] = formatMCPParamValue(v)
		}
	} else {
		// Route spec-declared in:query params to the query string for write
		// methods too. Without this, a query param (e.g. sendToLedger on
		// PUT /ledger/voucher/{id}) wrongly lands in the JSON body and the
		// API silently ignores it or rejects the request. The remaining
		// params stay in the map for codeOrchWriteBody (the JSON body).
		path = codeOrchSplitQuery(path, ep.QueryParams, params)
	}

	writeBody := func() any {
		if ep.BodyIsArray {
			return codeOrchArrayBody(params)
		}
		return codeOrchWriteBody(params)
	}
	var data json.RawMessage
	switch ep.Method {
	case "GET":
		if len(hdrs) > 0 {
			if ep.Mutating {
				data, err = c.GetMutatingWithHeaders(ctx, path, query, hdrs)
			} else {
				data, err = c.GetWithHeaders(ctx, path, query, hdrs)
			}
		} else {
			if ep.Mutating {
				data, err = c.GetMutating(ctx, path, query)
			} else {
				data, err = c.Get(ctx, path, query)
			}
		}
	case "DELETE":
		if len(hdrs) > 0 {
			data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, query, hdrs)
		} else {
			data, _, err = c.DeleteWithParams(ctx, path, query)
		}
	case "POST":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PostWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Post(ctx, path, body)
		}
	case "PUT":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PutWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Put(ctx, path, body)
		}
	case "PATCH":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PatchWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Patch(ctx, path, body)
		}
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	text := bound.EndpointResponse(ep.Method, data)
	if platformSession != nil {
		text = bound.WithMetadata(text, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(text), nil
}

// codeOrchWriteBody returns the value handed to the client layer as the
// request body for write methods (POST/PUT/PATCH). It MUST be the structured
// params map, never pre-marshaled bytes.
//
// client.do() marshals the body value exactly once. Handing it []byte makes
// json.Marshal([]byte) emit a base64-encoded JSON *string*, so the API
// receives "eyJ...==" where it expects the request object. Strict JSON APIs
// reject that as the wrong type at the body root. GET/DELETE carry no body,
// so this defect stays latent until the first write attempt.
func codeOrchWriteBody(params map[string]any) any {
	return params
}

// codeOrchArrayBody returns the request body for endpoints whose schema root
// is a bare top-level JSON array (ep.BodyIsArray). Such a body cannot be
// expressed as the params object, so the agent supplies the array under the
// conventional params key "body" (these endpoints have no flattened named
// params, so there is no collision risk). When present and array-shaped it is
// sent as the top-level array the API expects. Otherwise params is returned
// unchanged so a malformed call fails loudly at the API (HTTP 422) instead of
// silently sending the wrong shape or a partial write — financial mutations
// are never retried with body-variant guesses (broken-convenience guardrail).
func codeOrchArrayBody(params map[string]any) any {
	if v, ok := params["body"]; ok {
		if arr, ok := v.([]any); ok {
			return arr
		}
	}
	return params
}

// codeOrchSplitQuery removes spec-declared in:query params from params and
// appends them URL-encoded to the request path. The remaining
// entries stay in the map for codeOrchWriteBody (the JSON body), so a write
// method's query parameters never get buried in the body. Mutates params by
// design (deletes the consumed query keys).
func codeOrchSplitQuery(path string, queryParams []codeOrchParamBinding, params map[string]any) string {
	uv := neturl.Values{}
	for _, q := range queryParams {
		for _, key := range []string{q.PublicName, q.WireName} {
			if key == "" {
				continue
			}
			if v, ok := params[key]; ok {
				if q.QueryArray {
					path = appendMCPArrayQueryParam(path, q.WireName, v, q.QueryStyle, q.QueryExplode)
				} else {
					uv.Set(q.WireName, formatMCPParamValue(v))
				}
				delete(params, key)
				break
			}
		}
	}
	if enc := uv.Encode(); enc != "" {
		sep := "?"
		if strings.Contains(path, "?") {
			sep = "&"
		}
		path += sep + enc
	}
	return path
}

func codeOrchWireQueryName(queryParams []codeOrchParamBinding, name string) string {
	for _, q := range queryParams {
		if q.PublicName == name || q.WireName == name {
			return q.WireName
		}
	}
	return name
}
