// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL       string            `toml:"base_url"`
	AuthHeaderVal string            `toml:"auth_header"`
	Headers       map[string]string `toml:"headers,omitempty"`
	AuthSource    string            `toml:"-"`
	AccessToken   string            `toml:"access_token"`
	RefreshToken  string            `toml:"refresh_token"`
	TokenExpiry   time.Time         `toml:"token_expiry"`
	ClientID      string            `toml:"client_id"`
	ClientSecret  string            `toml:"client_secret"`
	// TokenURL overrides the spec-baked OAuth2 token endpoint. Same fallback
	// pattern as AuthorizationURL.
	TokenURL      string          `toml:"token_url,omitempty"`
	Path          string          `toml:"-"`
	envOverrides  map[string]bool `toml:"-"`
	fileConfig    *Config         `toml:"-"`
	HalopsaTenant string          `toml:"tenant"`
	HalopsaDomain string          `toml:"domain"`
	HalopsaScope  string          `toml:"scope"`
	HalopsaToken  string          `toml:"token"`
	// TemplateVars holds the runtime values for {placeholder} markers in
	// BaseURL and the request path (e.g. Shopify's {shop}/{version}). Populated
	// at Load() time from env vars; consumed by the client's buildURL helper.
	// Stored as a serializable map so non-default values survive a config save.
	TemplateVars map[string]string `toml:"template_vars,omitempty"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://{tenant}.{domain}/api",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("HALOPSA_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "halopsa-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	cfg.snapshotFileConfig()

	// Env var overrides
	if v := os.Getenv("HALOPSA_CLIENT_ID"); v != "" {
		cfg.ClientID = v
		cfg.markEnvOverride("ClientID")
		cfg.AuthSource = "env:HALOPSA_CLIENT_ID"
	}
	if v := os.Getenv("HALOPSA_CLIENT_SECRET"); v != "" {
		cfg.ClientSecret = v
		cfg.markEnvOverride("ClientSecret")
		cfg.AuthSource = "env:HALOPSA_CLIENT_SECRET"
	}
	if v := os.Getenv("HALOPSA_TENANT"); v != "" {
		cfg.HalopsaTenant = v
		cfg.markEnvOverride("HalopsaTenant")
		cfg.AuthSource = "env:HALOPSA_TENANT"
	}
	if v := os.Getenv("HALOPSA_DOMAIN"); v != "" {
		cfg.HalopsaDomain = v
		cfg.markEnvOverride("HalopsaDomain")
		cfg.AuthSource = "env:HALOPSA_DOMAIN"
	}
	if v := os.Getenv("HALOPSA_SCOPE"); v != "" {
		cfg.HalopsaScope = v
		cfg.markEnvOverride("HalopsaScope")
		cfg.AuthSource = "env:HALOPSA_SCOPE"
	}
	if v := os.Getenv("HALOPSA_TOKEN"); v != "" {
		cfg.HalopsaToken = v
		cfg.markEnvOverride("HalopsaToken")
		cfg.AuthSource = "env:HALOPSA_TOKEN"
	}

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "" || cfg.AccessToken != "") {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.HalopsaTenant != "" {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.HalopsaDomain != "" {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.HalopsaScope != "" {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.HalopsaToken != "" {
		cfg.AuthSource = "config"
	}

	// Soft agentcookie integration: if the agentcookie daemon manages this
	// CLI's secrets, it writes a marker file alongside the config file. When
	// the marker is present AND credentials came from the config (not from a
	// direct env var override that wins above), upgrade AuthSource to
	// "agentcookie" so doctor / auth-status can surface the bus state. When
	// the marker is absent, behavior is identical to pre-agentcookie: no
	// import, no network, no error. agentcookie itself is never imported
	// here — the contract is purely on-disk.
	if cfg.AuthSource == "config" {
		marker := filepath.Join(filepath.Dir(cfg.Path), ".agentcookie-managed")
		if _, err := os.Stat(marker); err == nil {
			cfg.AuthSource = "agentcookie"
		}
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("HALOPSA_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	if v := os.Getenv("HALOPSA_TOKEN_URL"); v != "" {
		cfg.TokenURL = v
	}

	// Endpoint template vars: resolve each {placeholder} in BaseURL or the
	// GraphQL path against the matching env var. Populated even when values
	// are empty so the client's buildURL helper can issue an actionable
	// "export FOO_BAR=..." error instead of silently sending a request to a
	// URL with literal "{shop}" in it. Under PRINTING_PRESS_VERIFY=1 (set by
	// the printing-press verifier in every mock subprocess), an unset
	// template var falls through to "<name>_placeholder" so dry-run legs
	// reach Cobra instead of hitting buildURL's actionable error first.
	// Placeholders with a spec-declared default (server-URL variables) skip
	// the verify branch; the default is a real value that lets verify probe
	// a real-shaped URL.
	if cfg.TemplateVars == nil {
		cfg.TemplateVars = map[string]string{}
	}
	if v := strings.TrimSpace(os.Getenv("HALOPSA_TENANT")); v != "" {
		cfg.TemplateVars["tenant"] = normalizeEndpointTemplateValue(v)
	} else {
		cfg.TemplateVars["tenant"] = "demo"
	}
	if v := strings.TrimSpace(os.Getenv("HALOPSA_DOMAIN")); v != "" {
		cfg.TemplateVars["domain"] = normalizeEndpointTemplateValue(v)
	} else {
		cfg.TemplateVars["domain"] = "halopsa.com"
	}
	return cfg, nil
}

// normalizeEndpointTemplateValue cleans up a server-URL template value the
// user has likely pasted from a browser address bar; drops the scheme prefix
// and trailing slash so a placeholder like {domain} resolves to a bare host
// whether the user typed `acme.example.com`, `https://acme.example.com`, or
// `https://acme.example.com/`. Applied only to placeholders carrying a
// spec-declared default (server-URL variables); path-positional placeholders
// like {tenant} pass through unchanged because their accepted shapes are
// API-specific.
func normalizeEndpointTemplateValue(v string) string {
	// Strip scheme prefix case-insensitively: users paste `HTTPS://` from
	// some browsers' address bars, and Go's TrimPrefix is exact-match.
	// Callers TrimSpace the env-var value before passing it in.
	if len(v) >= 8 && strings.EqualFold(v[:8], "https://") {
		v = v[8:]
	} else if len(v) >= 7 && strings.EqualFold(v[:7], "http://") {
		v = v[7:]
	}
	return strings.TrimRight(v, "/")
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	// Under OAuth2 (and bearer_token specs running OAuth grants such as
	// client_credentials or device_code) the configured env vars hold flow
	// inputs, not a usable bearer; the minted AccessToken must win. Sending
	// the client_id as Authorization: Bearer surfaces as token_rejected at
	// the API.
	if c.AccessToken != "" {
		if c.AuthSource == "" || strings.HasPrefix(c.AuthSource, "env:") {
			c.AuthSource = "oauth2"
		}
		return "Bearer " + c.AccessToken
	}
	return ""
}

// CanMintToken reports whether the client-credentials inputs are present.
//
// Mirrors the condition Client.authHeader already uses to decide whether to
// mint (both clientID and clientSecret non-empty), so doctor and the request
// path agree on what "configured" means.
func (c *Config) CanMintToken() bool {
	if c == nil {
		return false
	}
	return c.ClientID != "" && c.ClientSecret != ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	// issue #266: ClientID/ClientSecret supplied through the environment must
	// never be copied to the on-disk config. Load() marks them as env overrides
	// and configForSave() restores the file value for any field still marked --
	// clearing those two markers here defeated that, so every token mint,
	// including the automatic one on an ordinary authenticated command, rewrote
	// the live secret into ~/.config/<tool>-cli/config.toml in cleartext. The
	// markers now survive a save; only MarkCredentialsExplicit clears them.
	delete(c.envOverrides, "AccessToken")
	delete(c.envOverrides, "RefreshToken")
	delete(c.envOverrides, "TokenExpiry")
	c.updateFileConfigField("ClientID")
	c.updateFileConfigField("ClientSecret")
	c.updateFileConfigField("AccessToken")
	c.updateFileConfigField("RefreshToken")
	c.updateFileConfigField("TokenExpiry")
	return c.save()
}

// MarkCredentialsExplicit records that the caller supplied these credentials
// deliberately -- `auth login --client-id/--client-secret` -- rather than
// inheriting them from the environment, which permits the next SaveTokens to
// write them to disk. Provenance has to be declared by the caller: comparing
// the incoming value against the loaded one cannot tell an explicit flag from
// the environment value it happens to duplicate, and any normalisation on the
// way in (`auth login` trims its env fallback, Load does not) makes such a
// comparison wrong outright. See issue #266.
func (c *Config) MarkCredentialsExplicit(clientID, clientSecret bool) {
	if clientID {
		delete(c.envOverrides, "ClientID")
	}
	if clientSecret {
		delete(c.envOverrides, "ClientSecret")
	}
}

func (c *Config) ClearTokens() error {
	// AuthHeader() falls back to the env-var-derived fields when AuthHeaderVal
	// and AccessToken are empty, so dropping the working credential requires
	// zeroing every emitted credential field, not just the OAuth trio.
	// ClientID/ClientSecret persist to disk via SaveTokens for the oauth2
	// and oauth2-cc flows, so logout must wipe them too; otherwise
	// `auth login` can re-mint a new access token unattended.
	c.AuthHeaderVal = ""
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	delete(c.envOverrides, "AuthHeaderVal")
	delete(c.envOverrides, "AccessToken")
	delete(c.envOverrides, "RefreshToken")
	delete(c.envOverrides, "TokenExpiry")
	delete(c.envOverrides, "ClientID")
	delete(c.envOverrides, "ClientSecret")
	c.updateFileConfigField("AuthHeaderVal")
	c.updateFileConfigField("AccessToken")
	c.updateFileConfigField("RefreshToken")
	c.updateFileConfigField("TokenExpiry")
	c.updateFileConfigField("ClientID")
	c.updateFileConfigField("ClientSecret")
	c.HalopsaTenant = ""
	delete(c.envOverrides, "HalopsaTenant")
	c.HalopsaDomain = ""
	delete(c.envOverrides, "HalopsaDomain")
	c.HalopsaScope = ""
	delete(c.envOverrides, "HalopsaScope")
	c.HalopsaToken = ""
	delete(c.envOverrides, "HalopsaToken")
	return c.save()
}

func (c *Config) markEnvOverride(field string) {
	if c.envOverrides == nil {
		c.envOverrides = map[string]bool{}
	}
	c.envOverrides[field] = true
}

// cloneStringMap returns an independent copy of m (nil stays nil). The fileConfig
// snapshot must not share reference-type map fields (such as Headers) with the
// live config, or a later mutation to one would silently track in the other.
func cloneStringMap(m map[string]string) map[string]string {
	if m == nil {
		return nil
	}
	out := make(map[string]string, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

func (c *Config) snapshotFileConfig() {
	snapshot := *c
	snapshot.envOverrides = nil
	snapshot.fileConfig = nil
	// *c is a shallow copy: map fields are reference types, so the snapshot would
	// share them with c and silently track later mutations, defeating the
	// isolation this snapshot exists to provide. Clone them.
	snapshot.Headers = cloneStringMap(c.Headers)
	snapshot.TemplateVars = cloneStringMap(c.TemplateVars)
	c.fileConfig = &snapshot
}

func (c *Config) configForSave() Config {
	out := *c
	if c.fileConfig != nil {
		if c.envOverrides["ClientID"] {
			out.ClientID = c.fileConfig.ClientID
		}
		if c.envOverrides["ClientSecret"] {
			out.ClientSecret = c.fileConfig.ClientSecret
		}
		if c.envOverrides["HalopsaTenant"] {
			out.HalopsaTenant = c.fileConfig.HalopsaTenant
		}
		if c.envOverrides["HalopsaDomain"] {
			out.HalopsaDomain = c.fileConfig.HalopsaDomain
		}
		if c.envOverrides["HalopsaScope"] {
			out.HalopsaScope = c.fileConfig.HalopsaScope
		}
		if c.envOverrides["HalopsaToken"] {
			out.HalopsaToken = c.fileConfig.HalopsaToken
		}
	}
	out.envOverrides = nil
	out.fileConfig = nil
	return out
}

func (c *Config) updateFileConfigField(field string) {
	if c.fileConfig == nil || c.envOverrides[field] {
		return
	}
	switch field {
	case "AuthHeaderVal":
		c.fileConfig.AuthHeaderVal = c.AuthHeaderVal
	case "AccessToken":
		c.fileConfig.AccessToken = c.AccessToken
	case "RefreshToken":
		c.fileConfig.RefreshToken = c.RefreshToken
	case "TokenExpiry":
		c.fileConfig.TokenExpiry = c.TokenExpiry
	case "ClientID":
		c.fileConfig.ClientID = c.ClientID
	case "ClientSecret":
		c.fileConfig.ClientSecret = c.ClientSecret
	case "HalopsaTenant":
		c.fileConfig.HalopsaTenant = c.HalopsaTenant
	case "HalopsaDomain":
		c.fileConfig.HalopsaDomain = c.HalopsaDomain
	case "HalopsaScope":
		c.fileConfig.HalopsaScope = c.HalopsaScope
	case "HalopsaToken":
		c.fileConfig.HalopsaToken = c.HalopsaToken
	}
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	persisted := c.configForSave()
	data, err := toml.Marshal(persisted)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	if err := os.WriteFile(c.Path, data, 0o600); err != nil {
		return err
	}
	c.fileConfig = &persisted
	c.fileConfig.envOverrides = nil
	c.fileConfig.fileConfig = nil
	// persisted shares its map fields with c (configForSave shallow-copies *c),
	// so isolate the stored fileConfig the same way snapshotFileConfig does;
	// otherwise later mutations to c's maps leak into the on-disk snapshot.
	c.fileConfig.Headers = cloneStringMap(c.fileConfig.Headers)
	c.fileConfig.TemplateVars = cloneStringMap(c.fileConfig.TemplateVars)
	return nil
}

// Ensure strings import is used
var _ = strings.ReplaceAll
