// Copyright 2026 Damien Stevens and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL       string            `toml:"base_url"`
	AuthHeaderVal string            `toml:"auth_header"`
	Headers       map[string]string `toml:"headers,omitempty"`
	AuthSource    string            `toml:"-"`
	AccessToken   string            `toml:"access_token"`
	RefreshToken  string            `toml:"refresh_token"`
	TokenExpiry   time.Time         `toml:"token_expiry"`
	ClientID      string            `toml:"client_id"`
	ClientSecret  string            `toml:"client_secret"`
	TenantID      string            `toml:"tenant_id"`
	OAuthScope    string            `toml:"oauth_scope"`
	Authority     string            `toml:"authority"`
	Path          string            `toml:"-"`
	envOverrides  map[string]bool   `toml:"-"`
	fileConfig    *Config           `toml:"-"`
	CippApiKey    string            `toml:"api_key"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://your-cipp-instance.example.com",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("CIPP_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "cipp-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	cfg.snapshotFileConfig()

	// Env var overrides
	if v := os.Getenv("CIPP_API_KEY"); v != "" {
		cfg.CippApiKey = v
		cfg.markEnvOverride("CippApiKey")
		cfg.AuthSource = "env:CIPP_API_KEY"
	}

	// The client-credentials inputs, so a CIPP instance can be configured
	// entirely by environment instead of only through `auth login`. This is what
	// lets CIPP run as a service, and it matches the shape immybot already uses
	// (IMMYBOT_CLIENT_ID and friends). `auth login` is untouched and still the
	// right path on a laptop.
	//
	// Every one is markEnvOverride'd, so configForSave restores the file's value
	// and an env-supplied secret is never written to disk. That guard is why
	// #268 exists; ClientID and ClientSecret were previously file-only and so
	// were never covered by it.
	if v := os.Getenv("CIPP_CLIENT_ID"); v != "" {
		cfg.ClientID = v
		cfg.markEnvOverride("ClientID")
		if cfg.AuthSource == "" {
			cfg.AuthSource = "env:CIPP_CLIENT_ID"
		}
	}
	if v := os.Getenv("CIPP_CLIENT_SECRET"); v != "" {
		cfg.ClientSecret = v
		cfg.markEnvOverride("ClientSecret")
		if cfg.AuthSource == "" {
			cfg.AuthSource = "env:CIPP_CLIENT_SECRET"
		}
	}
	if v := os.Getenv("CIPP_TENANT_ID"); v != "" {
		cfg.TenantID = v
		cfg.markEnvOverride("TenantID")
	}
	if v := os.Getenv("CIPP_OAUTH_SCOPE"); v != "" {
		cfg.OAuthScope = v
		cfg.markEnvOverride("OAuthScope")
	}
	if v := os.Getenv("CIPP_AUTHORITY"); v != "" {
		cfg.Authority = v
		cfg.markEnvOverride("Authority")
	}

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "" || cfg.AccessToken != "") {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.CippApiKey != "" {
		cfg.AuthSource = "config"
	}

	// Soft agentcookie integration: if the agentcookie daemon manages this
	// CLI's secrets, it writes a marker file alongside the config file. When
	// the marker is present AND credentials came from the config (not from a
	// direct env var override that wins above), upgrade AuthSource to
	// "agentcookie" so doctor / auth-status can surface the bus state. When
	// the marker is absent, behavior is identical to pre-agentcookie: no
	// import, no network, no error. agentcookie itself is never imported
	// here — the contract is purely on-disk.
	if cfg.AuthSource == "config" {
		marker := filepath.Join(filepath.Dir(cfg.Path), ".agentcookie-managed")
		if _, err := os.Stat(marker); err == nil {
			cfg.AuthSource = "agentcookie"
		}
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("CIPP_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	// Env-var token wins over file-stored AccessToken (env > config convention).
	if c.CippApiKey != "" {
		if c.AuthSource == "" {
			c.AuthSource = "env:CIPP_API_KEY"
		}
		return "Bearer " + c.CippApiKey
	}
	if c.AccessToken != "" {
		if c.AuthSource == "" || strings.HasPrefix(c.AuthSource, "env:") {
			c.AuthSource = "oauth2"
		}
		return "Bearer " + c.AccessToken
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	delete(c.envOverrides, "ClientID")
	delete(c.envOverrides, "ClientSecret")
	delete(c.envOverrides, "AccessToken")
	delete(c.envOverrides, "RefreshToken")
	delete(c.envOverrides, "TokenExpiry")
	c.updateFileConfigField("ClientID")
	c.updateFileConfigField("ClientSecret")
	c.updateFileConfigField("AccessToken")
	c.updateFileConfigField("RefreshToken")
	c.updateFileConfigField("TokenExpiry")
	return c.save()
}

func (c *Config) ClearTokens() error {
	// AuthHeader() falls back to the env-var-derived fields when AuthHeaderVal
	// and AccessToken are empty, so dropping the working credential requires
	// zeroing every emitted credential field, not just the OAuth trio.
	// ClientID/ClientSecret persist to disk via SaveTokens for the oauth2
	// and oauth2-cc flows, so logout must wipe them too; otherwise
	// `auth login` can re-mint a new access token unattended.
	c.AuthHeaderVal = ""
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	delete(c.envOverrides, "AuthHeaderVal")
	delete(c.envOverrides, "AccessToken")
	delete(c.envOverrides, "RefreshToken")
	delete(c.envOverrides, "TokenExpiry")
	delete(c.envOverrides, "ClientID")
	delete(c.envOverrides, "ClientSecret")
	c.updateFileConfigField("AuthHeaderVal")
	c.updateFileConfigField("AccessToken")
	c.updateFileConfigField("RefreshToken")
	c.updateFileConfigField("TokenExpiry")
	c.updateFileConfigField("ClientID")
	c.updateFileConfigField("ClientSecret")
	c.CippApiKey = ""
	delete(c.envOverrides, "CippApiKey")
	return c.save()
}

func (c *Config) markEnvOverride(field string) {
	if c.envOverrides == nil {
		c.envOverrides = map[string]bool{}
	}
	c.envOverrides[field] = true
}

// cloneStringMap returns an independent copy of m (nil stays nil). The fileConfig
// snapshot must not share reference-type map fields (such as Headers) with the
// live config, or a later mutation to one would silently track in the other.
func cloneStringMap(m map[string]string) map[string]string {
	if m == nil {
		return nil
	}
	out := make(map[string]string, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

func (c *Config) snapshotFileConfig() {
	snapshot := *c
	snapshot.envOverrides = nil
	snapshot.fileConfig = nil
	// *c is a shallow copy: map fields are reference types, so the snapshot would
	// share them with c and silently track later mutations, defeating the
	// isolation this snapshot exists to provide. Clone them.
	snapshot.Headers = cloneStringMap(c.Headers)
	c.fileConfig = &snapshot
}

func (c *Config) configForSave() Config {
	out := *c
	if c.fileConfig != nil {
		// An env-supplied credential must never reach the file. Each field is
		// restored from the on-disk snapshot when the live value came from the
		// environment.
		if c.envOverrides["CippApiKey"] {
			out.CippApiKey = c.fileConfig.CippApiKey
		}
		if c.envOverrides["ClientID"] {
			out.ClientID = c.fileConfig.ClientID
		}
		if c.envOverrides["ClientSecret"] {
			out.ClientSecret = c.fileConfig.ClientSecret
		}
		if c.envOverrides["TenantID"] {
			out.TenantID = c.fileConfig.TenantID
		}
		if c.envOverrides["OAuthScope"] {
			out.OAuthScope = c.fileConfig.OAuthScope
		}
		if c.envOverrides["Authority"] {
			out.Authority = c.fileConfig.Authority
		}
	}
	out.envOverrides = nil
	out.fileConfig = nil
	return out
}

func (c *Config) updateFileConfigField(field string) {
	if c.fileConfig == nil || c.envOverrides[field] {
		return
	}
	switch field {
	case "AuthHeaderVal":
		c.fileConfig.AuthHeaderVal = c.AuthHeaderVal
	case "AccessToken":
		c.fileConfig.AccessToken = c.AccessToken
	case "RefreshToken":
		c.fileConfig.RefreshToken = c.RefreshToken
	case "TokenExpiry":
		c.fileConfig.TokenExpiry = c.TokenExpiry
	case "ClientID":
		c.fileConfig.ClientID = c.ClientID
	case "ClientSecret":
		c.fileConfig.ClientSecret = c.ClientSecret
	case "CippApiKey":
		c.fileConfig.CippApiKey = c.CippApiKey
	case "TenantID":
		c.fileConfig.TenantID = c.TenantID
	case "OAuthScope":
		c.fileConfig.OAuthScope = c.OAuthScope
	case "Authority":
		c.fileConfig.Authority = c.Authority
	}
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	persisted := c.configForSave()
	data, err := toml.Marshal(persisted)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	if err := os.WriteFile(c.Path, data, 0o600); err != nil {
		return err
	}
	c.fileConfig = &persisted
	c.fileConfig.envOverrides = nil
	c.fileConfig.fileConfig = nil
	// persisted shares its map fields with c (configForSave shallow-copies *c),
	// so isolate the stored fileConfig the same way snapshotFileConfig does;
	// otherwise later mutations to c's maps leak into the on-disk snapshot.
	c.fileConfig.Headers = cloneStringMap(c.fileConfig.Headers)
	return nil
}

// Ensure strings import is used
var _ = strings.ReplaceAll

// DefaultAuthority is Azure AD's public cloud endpoint. Sovereign clouds set
// CIPP_AUTHORITY or the authority field in config.toml.
const DefaultAuthority = "https://login.microsoftonline.com"

// tokenRefreshSkew re-mints slightly early so a token cannot expire in flight
// between the check and the API call it authorizes.
const tokenRefreshSkew = 2 * time.Minute

// CanMintToken reports whether the client-credentials inputs are all present,
// whatever their source: environment for a container, config.toml for a laptop
// that has run `auth login`.
func (c *Config) CanMintToken() bool {
	return c.ClientID != "" && c.ClientSecret != "" && c.TenantID != ""
}

// TokenNeedsRefresh reports whether the cached access token is missing or close
// enough to expiry to be untrustworthy.
//
// Nothing consulted TokenExpiry before this. `auth login` cached a token and its
// expiry, the client read only the token, and an Azure AD client-credentials
// token lives about an hour, so CIPP worked for an hour and then returned 401
// until someone ran `auth login` again. That is a laptop bug as much as a
// container one; it is simply unmissable when the process is meant to stay up.
func (c *Config) TokenNeedsRefresh() bool {
	if c.CippApiKey != "" || c.AuthHeaderVal != "" {
		// A static bearer token was supplied deliberately. Not ours to refresh.
		return false
	}
	if c.AccessToken == "" {
		return true
	}
	if c.TokenExpiry.IsZero() {
		// Cached by a build that did not record an expiry. Leave it alone rather
		// than re-minting on every call.
		return false
	}
	return time.Now().After(c.TokenExpiry.Add(-tokenRefreshSkew))
}

// EffectiveScope returns the configured OAuth2 scope, defaulting to the same
// value `auth login` derives.
func (c *Config) EffectiveScope() string {
	if c.OAuthScope != "" {
		return c.OAuthScope
	}
	if c.ClientID == "" {
		return ""
	}
	return "api://" + c.ClientID + "/.default"
}

// EffectiveAuthority returns the configured authority or the public cloud.
func (c *Config) EffectiveAuthority() string {
	if c.Authority != "" {
		return c.Authority
	}
	return DefaultAuthority
}

// ApplyMintedToken records a freshly minted token in memory only.
//
// Deliberately not persisted. `auth login` is an explicit act by a human and
// writes to disk; an automatic refresh on a read path is not, and writing there
// would put a live credential into the volume an operator backs up. A
// long-running server mints once per token lifetime, which is cheap.
func (c *Config) ApplyMintedToken(token string, expiry time.Time) {
	c.AccessToken = token
	c.TokenExpiry = expiry
	c.AuthSource = "oauth2"
}
